### ISSUE TITLE
#define statement for different devices selection doesn't work

### ISSUE THREAD

**Issue by MustafaFayez** [z3t0/Arduino-IRremote#117]
You said to keep the size of the library manageable you're moving to a model where different device types use a #define statement, for instance:
# define SHARP

where is that ? and how you will do it ?

**Comment by z3t0** [comment]
@MustafaFayez I understand your confusion as we have not made this very clear yet, I am working on a set of tutorials to clear this up and will release the next version at the same time. For now please use the latest Release, which does not yet need #define statements.

**Comment by MustafaFayez** [comment]
@z3t0 I searched for this issue online, some people say it won't work:
http://stackoverflow.com/questions/14418936/arduino-overriding-define-in-libraries

**Comment by z3t0** [comment]
@MustafaFayez That's what I thought too, but apparently it did work and provide results...
Check #99 and #110

**Comment by z3t0** [comment]
@MustafaFayez We did end up using #defines so I'm getting confused as to how they actually worked...
You'll see what I meant if you read #110 because we actually have it working there.

**Comment by MustafaFayez** [comment]
@z3t0 I read #110, great work there,but did you use #define in arduino sketch or just in .h file as in #110 ?? In other words, can the user selects the library code to be compiled from sketch or not?

**Comment by z3t0** [comment]
@MustafaFayez I see what you mean, I will do some testing my self and see what I can come up with. Thank you very much for pointing this out

**Comment by MustafaFayez** [comment]
@z3t0 any updates?

**Comment by z3t0** [comment]
Sorry got side tracked. I'll get back on it. 

--
Thanks,
Rafi Khan 

----- Reply message -----

**Comment by z3t0** [comment]
Still working on it... Sorry got a lot of things distracting me.

**Comment by AllAboutEE** [comment]
According to #99 it only works in sublime, and it's just bad practice over all. I'll separate the functions into different files and submit a pull request, I know it was said in #100 that it breaks the Arduino convention of including only one library but I'm sure people will understand.

**Comment by z3t0** [comment]
Yep, this is quite a big priblem and we are yet to find an ideal solution.

----- Reply message -----

**Comment by AllAboutEE** [comment]
I think I found one: I'm going to use namespaces instead of defines, that way we can keep the one file include statement and do "using namespace NEC" instead of "#define SEND_NEC" which does not work.
