### ISSUE TITLE
ifdefs for decoding JVC and LG mixed up

### ISSUE THREAD

**Issue by levsa** [z3t0/Arduino-IRremote#121]
ifdefs for decoding JVC and LG are mixed up

```c++
#ifdef JVC // should be LG
#ifdef DEBUG
    Serial.println("Attempting LG decode");
#endif
    if (decodeLG(results)) {
        return DECODED;
    }
// missing #endif here
// missing #ifdef JVC here
#ifdef DEBUG
    Serial.println("Attempting JVC decode");
#endif
    if (decodeJVC(results)) {
        return DECODED;
    }
#endif
```

**Comment by joshuajnoble** [comment]
Could you create an pull request for this?

**Comment by levsa** [comment]
I think this was this fixed by my other pull request?

**Comment by joshuajnoble** [comment]
It was, my bad!

On Sun, Apr 12, 2015 at 12:25 PM, Levon Saldamli <notifications@github.com>
wrote:

> I think this was this fixed by my other pull request?
>
> On Fri, Apr 10, 2015, 19:45 joshua noble <notifications@github.com> wrote:
>
> > Could you create an pull request for this?
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/shirriff/Arduino-IRremote/issues/121#issuecomment-91633988
> >
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/shirriff/Arduino-IRremote/issues/121#issuecomment-92030909>
> .
>



-- 
joshua noble
http://thefactoryfactory.com
