### ISSUE TITLE
Extra #endif after IRrecv::getRClevel()

### ISSUE THREAD

**Issue by levsa** [z3t0/Arduino-IRremote#123]
There seems to be an extra #endif after IRrecv::getRClevel(). Probably makes up for missing #endif for SAMSUNG (see issue #122)

**Comment by joshuajnoble** [comment]
Could you create a pull request for this?

**Comment by levsa** [comment]
I think this was this fixed by my other pull request?

**Comment by z3t0** [comment]
@levsa Umm was it? Lol you did author the PR haha

**Comment by z3t0** [comment]
I think this was fixed along the way somewhere...
