### ISSUE TITLE
Turn into RAW

### ISSUE THREAD

**Issue by Zhenit-606** [z3t0/Arduino-IRremote#132]
Hello guys, before I want to thank immensely for the wonderful library that you develop and maintain. This tool helps many, many people, thank you.

I'm new in electronics and programming (30 days), and start a laser-tag project, the prototype is already up and running. To communicate i using a modified version of irRemote. I cleaned everything leaving only send.SONY, send.RAW and reception.
I'm currently using the transmitting send.SONY, but as the trigger occurs several times, I would send with send.RAW using the same standard of SONY. So I ask your help to do a small code to add in my sketch that turns the value of a variable long in RAW times, for me to send with send.RAW.

Example:
unsigned long turnraw = 123456;
unsigned int sendraw[];
I need a code to turn the turnraw in RAW times based on SONY and store in sendraw.

Excuse my english, I am using Google translator, I hope you understand.
Thanks for listening.

**Comment by z3t0** [comment]
@Zhenit-606 Firstly I would like to apologize that no one has replied to your issue until now, I would have replied but have been immensely busy lately. I will take a look and see what I can do, I am no expert with the ir code in this library but I will do my best! @joshuajnoble Any ideas?

**Comment by z3t0** [comment]
This may be beyond the scope of this library, but instead something for a helper application?
