### ISSUE TITLE
Customise

### ISSUE THREAD

**Issue by brahbassim** [z3t0/Arduino-IRremote#149]
Please how to customize the library to handle other brands? i have a TV witch is Hisense , and this library don't handle Hisense brand  . So i want an issue for this problem, and in future every one could customize and add new brands.

**Comment by csBlueChip** [comment]
Yes, I've noticed my DENON and my XBOX(original) remotes produce "UNKNOWN" ...A little article on this would be very useful and I will certainly submit my findings for inclusion :)

**Comment by z3t0** [comment]
I will work on a small guide very soon.

**Comment by csBlueChip** [comment]
Just stumbled across these:
"Old" Panasonic (22 bits) : http://users.telenet.be/davshomepage/panacode.htm
RC5 : http://users.telenet.be/davshomepage/rc5.htm
Daewoo : http://users.telenet.be/davshomepage/daewoo.htm
Sony : http://users.telenet.be/davshomepage/sony.htm
JVC : http://users.telenet.be/davshomepage/jvc.htm
I've not studied them all yet, but I imagine that doing so will lend an idea to decoding other formats too.

**Comment by z3t0** [comment]
@brahbassim Check the ir_template.cpp

**Comment by z3t0** [comment]
Feel free to re-open if you need particular help
