### ISSUE TITLE
NEC frequency (actually repetition and not frequency)

### ISSUE THREAD

**Issue by dandroid88** [z3t0/Arduino-IRremote#16]
Hi Ken (all),

I have been trying to use this library with my Pioneer stereo (VSX-521-K) however I was having issues.  It uses one of the NEC protocols however the modulation frequency is not 38 khz.  I added a loop to go from 36khz through 41 khz and that solved it.  I don't necessarily think this is what you would want to bake into the library however I was thinking about adding a "freq" parameter to the various send commands such that someone using this library could do what I did without modifying the underlying library.  Naturally, there could be a sendPioneer function but this doesn't seem like a very good solution, seems like feeding the freq in would be better.

I was thinking about forking and pushing back with the aforementioned changes.  Does this suggestion make sense?
Cheers,
Dan

**Comment by z3t0** [comment]
Solved
