### ISSUE TITLE
Disabling protocols is not working

### ISSUE THREAD

**Issue by gaetanwalter** [z3t0/Arduino-IRremote#178]
When you disable protocols using
#define DECODE_RC5           0

the sketch can't compile because in irRecv:

#ifdef DECODE_RC5
	DBG_PRINTLN("Attempting RC5 decode");
	if (decodeRC5(results))  return true ;
#endif

should be:

#if DECODE_RC5
	DBG_PRINTLN("Attempting RC5 decode");
	if (decodeRC5(results))  return true ;
#endif

And ir_RC5_RC6.cpp, the metchod: IRrecv::getRClevel should be in a :

#if (DECODE_RC5 || DECODE_RC6)
#endif

**Comment by z3t0** [comment]
Thanks, will take care of this and commit upstream

**Comment by z3t0** [comment]
@gaetanwalter Do you know if this is a problem for other protocols as well? Thanks

**Comment by gaetanwalter** [comment]
Yeah, all ifdef schould be if

DECODE_XXX is defined (as 0 or 1) so ifdef will always return true.

**Comment by z3t0** [comment]
@gaetanwalter Great, will fix this tomorrow.

**Comment by z3t0** [comment]
@gaetanwalter Committed. 5c920bd31dead97ce9acfc6429b9c3e0162faf47
