### ISSUE TITLE
IR Multiple Receiver Issues with Timer (@khair-eddine fork)

### ISSUE THREAD

**Issue by domonation** [z3t0/Arduino-IRremote#180]
Has anyone else had an issue with the timers? I am currently implementing 4 receivers but when I attempt to use the millis() function it gives me a constant value. I am using an Arduino Mega 2560

Sketch:
```c
//#include<SoftwareServo.h>
#include <VirtualWire.h>
//#include <EEPROM.h>
#include "IRremote.h"
#include "CppList.h"

/////////////////////////////
/// Initialize Receivers ///
bool _initialized = false;
int rcv_count;
IRrecv **all_rcv;
///////////////////////////////

// Declare L298N Dual H-Bridge Motor Controller directly since there is not a library to load.
#define trigPin 12
#define echoPin 11
#define RX_DIO_PIN 2

int lastcommand = 0;
unsigned int speed1 = 0;
int dist, pwm1 = 0;
unsigned int encoder0Pos = 0;
unsigned long oldtime;
long duration, distance;
long duration2, distance2;

unsigned int totalran, lasttime = 0;


unsigned long lasttimeir; 
unsigned int timeran;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
void setup() {  // Setup runs once per reset

vw_set_rx_pin(RX_DIO_PIN);   //setup receiver
vw_set_ptt_inverted(true);
vw_setup(4000);
vw_rx_start();
  pwm1 = 54; 
  ////////////////////////////////////////////////////
  
// initialize serial communication @ 9600 baud:
Serial.begin(115200);
pinMode(trigPin, OUTPUT);
pinMode(echoPin, INPUT);

//// Initialize the IR sensors/////////////////////////////////////

 /*if (_initialized) return;
  rcv_count = 4;
  all_rcv = (IRrecv **)malloc(rcv_count*sizeof(int));
   all_rcv[0] = new IRrecv(44);
  all_rcv[1] = new IRrecv(48);
  all_rcv[2] = new IRrecv(46);
  all_rcv[3] = new IRrecv(47);
  
  
  for (int i=0; i<rcv_count; ++i){
    all_rcv[i]->enableIRIn();
  }

  _initialized = true;*/
  ////////////////////////////////////////////////////

//define L298N Dual H-Bridge Motor Controller Pins

}




////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  

void loop() {
  
  Serial.print("Getting Distance   Millis: ");
 Serial.println(millis()); 
float distance1 = getDistance(); 
Serial.println(distance1); 
 delay(1000); 
  
}
   
//////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////
     

      

float getDistance(){
      
  digitalWrite(trigPin, LOW);
 delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
 delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  float distance = (duration/2)/22.2;
  return distance;
}
```

**Comment by z3t0** [comment]
@domonation Can you please post the full sketch into a gist and share it here. Also, are you doing anything else with the Arduino while trying to get the 4 receivers to work? I mean has the problem been isolated to the library/receiver or are there additional shields which are also attached? Thanks

**Comment by z3t0** [comment]
@domonation Do you know which timer is being used for the different receivers? Which pins? (If it is realistic could you make a rough schematic or post a photo?)

**Comment by z3t0** [comment]
Also I'm assuming it works fine when not using the IR library?

**Comment by domonation** [comment]
I am using an Arduino Mega 2560 with 4 receivers while simultaneously emitting an IR signal. What I have done however is used an Attiny 85 to handle the emitting portion. What I am doing is essentially using the 4 receivers covering different quadrants in order to help the car navigate towards an IR beacon. I am also incorporating an ultrasonic sensor. On the mega the pins were connected to pins 42, 44-46.

As you can see from the sketch that the receiver initialization is commented out. Printing out millis() and obtaining an accurate distance works perfectly, but as soon as I remove the comment, the delays and printed millis() value are not what is desired which in turn affects the ultrasonic sensor. 

I am currently using a Nano that a friend had lying around to handle the receiving portion and I simply send over to the mega which receiver detects the signal. The problem with the nano however is that it can only handle 3 receivers stably.

**Comment by z3t0** [comment]
@domonation Sorry for the delay, will get back to you ASAP (have been out for a few days_

**Comment by z3t0** [comment]
@domonation Sorry for not being much help... I really don't know what is going on and also do not know too much about the Multiple Receiver Fork as it isn't very robust or production ready... I am working on a multiple receiver implementation of my own and hopefully that will work for you, in the meantime you could converse with @khair-eddine as he may know more about this particular topic.

**Comment by z3t0** [comment]
@domonation Take a look at the patch in #184 as it may prove useful

**Comment by z3t0** [comment]
Closing as there has been no response for over three weeks. Please re-open if your issue has not been solved
