### ISSUE TITLE
Enabling Larger Raw Code Lengths

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#187]
Refer to #51 for more information.

The following is quoted from @Analysir:

To be able to handle long AC signals, setting RAWBUF to 256 will still miss most of them.
(I believe RAWBUF is still limited to a max length of 256)

However, it would be useful if users could at least (dynamically) set RAWBUF length from their own code without having to dig into & modify the library files.

As a workaround we have offered an alternative sketch via our blog which is extremely popular and which handles long AC signals on most standard arduinos. Feel free to link to that as a standalone sketch, for long AC signals.
http://www.analysir.com/blog/2014/03/19/air-conditioners-problems-recording-long-infrared-remote-control-signals-arduino/

If you want to include it with the library as a standalone sketch/example/utility, just be sure to provide a link back to the original article on our site, with the usual credits etc.

(PS: I don't foresee a situation (in the sort term) where you will have a generic library for recording & decoding multiple AC signals on standard Arduinos. The best/likely target is to be able to record RAW AC signals.)

**Comment by ArminJo** [comment]
I changed rawlen from uint8_t to unsigned int allowing bigger receive buffer.
