### ISSUE TITLE
999 Stars

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#188]
Just wanted to make a quick issue to celebrate the fact that we have 999 stars!

All thanks go to the contributors!

@shirriff @Informatic @fmeschia @PaulStoffregen @crash7 @zenwheel @Neco777 @Lauszus @csBlueChip @joshuajnoble @sstefanov @levsa 

AND EVERYONE ELSE I MISSED... feel free to comment and let me know.

**Comment by crash7** [comment]
good job guys! :+1:
