### ISSUE TITLE
The IRsendDemo.ino does not demo IRsend

### ISSUE THREAD

**Issue by baget** [z3t0/Arduino-IRremote#195]
The IRSend Demo  does not show example on how to send IR
it show code that is not related to IRsend.
https://github.com/z3t0/Arduino-IRremote/blob/master/examples/IRsendDemo/IRsendDemo.ino

````
#include <IRremote.h>

int RECV_PIN = 11;
IRrecv irrecv (RECV_PIN);

void setup()
{
  Serial.begin(115200);
}

void loop() {
  if (irrecv.isIdle())
  Serial.println("Idling");
}
````

**Comment by z3t0** [comment]
Will fix right away, must have changed during one of my commits..

**Comment by z3t0** [comment]
The above commit should fix the problem
