### ISSUE TITLE
JVC commands need to be sent three times

### ISSUE THREAD

**Issue by probonopd** [z3t0/Arduino-IRremote#21]
This is just to let others know that some JVC devices (in my case, a 2007 JVC TFT TV) apparently ignore commands if they are not sent three times with appropriate timing in between. To me this was not clear from reading the JVC spec at http://support.jvc.com/consumer/support/documents/RemoteCodes.pdf so I spent a lot of time and in the end found the solution by comparing what the original remote sends to what the sketch sends using a USB sound card "oscilloscope" and Audacity.

Here is code that works for me:

```
// Mute = 0xC038 (command needs to be sent three times!) - works
unsigned int jvc[104] =  {
8400, 4220,                               // Header
527, 1583, 527, 1583, 527, 527, 527, 527, // 1100 =, 0xC
527, 527, 527, 527, 527, 527, 527, 527,   // 0000 =, 0x0
527, 527, 527, 527, 527, 1583, 527, 1583, // 0011 =, 0x3
527, 1583, 527, 527, 527, 527, 527, 527,  // 1000 =, 0x8
527, 75000,                               // Pause
527, 1583, 527, 1583, 527, 527, 527, 527, // 1100 =, 0xC
527, 527, 527, 527, 527, 527, 527, 527,   // 0000 =, 0x0
527, 527, 527, 527, 527, 1583, 527, 1583, // 0011 =, 0x3
527, 1583, 527, 527, 527, 527, 527, 527,  // 1000 =, 0x8
527, 75000,                               // Pause
527, 1583, 527, 1583, 527, 527, 527, 527, // 1100 =, 0xC
527, 527, 527, 527, 527, 527, 527, 527,   // 0000 =, 0x0
527, 527, 527, 527, 527, 1583, 527, 1583, // 0011 =, 0x3
527, 1583, 527, 527, 527, 527, 527, 527,  // 1000 =, 0x8
527, 75000                                // Footer
};
```

Or, using the built-in function:

```
void sendJVC(long command)
{
  // JVC commands need to be sent three times with 75 ms pause in between
  irsend.sendJVC(command, 16, 0); // 0 = with lead-in
  delayMicroseconds(75); 
  irsend.sendJVC(command, 16, 1); // 1 = without lead-in
  delayMicroseconds(75); 
  irsend.sendJVC(command, 16, 1); 
}
```

**Comment by z3t0** [comment]
I will work on adding this very soon.

**Comment by AnalysIR** [comment]
@probonopd good spot...

However as the spec does not state that the bust 'must' be repeated 3 times - should we not allow for both options and either put a note in to say that some systems may require the burst to be sent 3 times or alternaively just put a parameter into the function call for the number  of times to repeat, with a default of 1 e.g.

````void sendJVC(long command, unsigned char repeats)````

I guess whoever added this in originally had it working with just the one burst!

**Comment by ElectricRCAircraftGuy** [comment]
I recommend making a JVC example sketch with plenty of comments, that properly sends the commands 3 times, but **not** enforcing this at the low level inside the library. Not all devices necessarily follow such protocols and you don't want the library to override everything. Additonally, some people (myself) included, use IR libraries to send custom, digital data streams (ex: commands, files, text, images, whatever), using any given protocol, and any protocol that enforces 3 sends in the library automatically can't be used to send custom digital data streams. I'm using the Sony protocol right now to send 32 bit command packets to an RC/robotic car.

**Comment by z3t0** [comment]
@ElectricRCAircraftGuy Thanks I will keep that in minde

**Comment by bobman38** [comment]
Hello

Just dropping some lines here about a JVC Mini-System that I have. The data present on irdb.tk was working with the specific arduino sketch, but not via this IRremote lib. After study it seems that I need to send the code twice, with 20 milli-seconds between:

`  irsend.sendJVC(JVC_POWER_ON, 16,0); // hex value, 16 bits, no repeat
  delay(20);
  irsend.sendJVC(JVC_POWER_ON, 16,1); // hex value, 16 bits, repeat`

(device is 163)

Yeah, life is hard ;) detected by analyzing the pronto hex from irdb.tk via IrScrutinizer.

**Comment by probonopd** [comment]
> After study it seems that I need to send the code twice, with 20 milli-seconds between

What happens if you send three times with 75 ms in between? Just curious, because this is what my original JVC remote does.
