### ISSUE TITLE
NEC sending signal twice

### ISSUE THREAD

**Issue by trunner10** [z3t0/Arduino-IRremote#210]
When I use the sendNEC command it sends the ir command twice.  So when i try to change the channel it changes it twice.  Is there a way to not send the command twice or am i doing something wrong.  Thanks  

--Update 8-26-2015---
What im trying to do is change the channel on my tivo from a web request.  It works except for the fact that it sends the signal twice and i havent been able to figure out why.  I did try using the just the IRsendDemo and changing it to irsend.sendNEC(0xA10C6C03, 32); // Tivo guide code 
and removing the for loop and it worked correctly so it looks like there is nothing wrong with the irsend.sendNEC command like i first thought.  So the issue probably has to be in the way the arduino is receiving the command from the web.  I realize this is not what this github is for so i understand if you dont have time to help me out.  But if you would like to take a look at the code here is the link.

https://gist.github.com/trunner10/fd5516aa7533a7168aee

thank you for any help you can provide.

**Comment by AnalysIR** [comment]
Based on the information you provided, you are probably doing something wrong...

...more information, like your code would help.

**Comment by z3t0** [comment]
@trunner10 Please edit your comment with a link to a gist containing your sketch.

**Comment by AnalysIR** [comment]
you are probably not parsing the incoming http header & get request properly. the text in the get request is likely causing your case statement to mis-fire....I could be wrong as i didn't spend much time on it and your are right....you may be better posting on the Arduino forum.

**Comment by z3t0** [comment]
@trunner10 Would love to help but I have never played around with the web and arduino. I will take a look at your code and see if I notice anything.
