### ISSUE TITLE
Attiny85 support

### ISSUE THREAD

**Issue by lechacal** [z3t0/Arduino-IRremote#220]
Hi all,

Thank you for the great library. Has anyone been running the library on Attiny85 before?

I have had my first try but realised it might not have full support yet.

I am also asking some help on the Arduino forum here. http://forum.arduino.cc/index.php?topic=346847

**Comment by lechacal** [comment]
For now just a yes/no answer to say whether the library currently supports attiny85 or not would be great.

**Comment by z3t0** [comment]
please check #97

On Fri, Sep 11, 2015 at 8:58 AM, lechacal <notifications@github.com> wrote:

> For now just a yes/no answer to say whether the library currently supports
> attiny85 or not would be great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/z3t0/Arduino-IRremote/issues/220#issuecomment-139568227>
> .
>



-- 
Thanks,
Rafi Khan

**Comment by z3t0** [comment]
and #39

On Fri, Sep 11, 2015 at 12:40 PM, Rafi Khan <zetoslab@gmail.com> wrote:

> please check #97
>
> On Fri, Sep 11, 2015 at 8:58 AM, lechacal <notifications@github.com>
> wrote:
>
>> For now just a yes/no answer to say whether the library currently
>> supports attiny85 or not would be great.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/z3t0/Arduino-IRremote/issues/220#issuecomment-139568227>
>> .
>>
>
>
>
> --
> Thanks,
> Rafi Khan
>
>


-- 
Thanks,
Rafi Khan

**Comment by madmalkav** [comment]
I have it running on Attiny85 but the library blocks SoftSerial. I.E. if I have a loop writing a message a serial like "Waiting for IR signal", as soon as an IR signal arrives, the serial outputs stops. IR receiving is working ok as the feedback LED is working.

**Comment by AnalysIR** [comment]
Maybe time to upgrade the MCU being used to one with more resources???

**Comment by madmalkav** [comment]
It works ok with another IR library so I don't think it is a lack of
resources problem

**Comment by AnalysIR** [comment]
The other library(?) may not be using the same peripherals(timers).

**Comment by madmalkav** [comment]
Yeah, now that you say, it is probably that.

**Comment by joshuajnoble** [comment]
I looked into this and IIRC to get this library working with the timers available on the ATTiny85 would require a pretty substantial rewrite of the library that I haven't had time for, sadly.

**Comment by cklim01** [comment]
Can IRremote and Softwareserial use in same sketch on Attiny85?

**Comment by z3t0** [comment]
@cklim01 Do you know which timer is used by Software Serial?

**Comment by cklim01** [comment]
Sorry @z3t0 , i have no idea about it. i have very limited knowledge about mcu and programming. just started to learn.

**Comment by PaulStoffregen** [comment]
SoftwareSerial doesn't use any timers on AVR chips.

But it does block interrupts, so it'll play havoc with IRremote's receive code which depends on a timer interrupt at regular intervals.  It'll also mess up IRremote transmitting if a character arrives and SoftwareSerial takes too much CPU time with its interrupt while IRremote is delaying to generate IR bursts at the correct speeds.

**Comment by PaulStoffregen** [comment]
If you're using slow baud rates, my AltSoftSerial library might be an alternative.  But it requires a 16 bit timer, and my understanding is the ATTINY chips usually have only 8 bit timers, so you might be out of luck there too unless you're using an AVR with a 16 bit timer.

**Comment by cklim01** [comment]
That too bad. need to use other AVR. Anyway, thanks for your info.

**Comment by z3t0** [comment]
> SoftwareSerial doesn't use any timers on AVR chips.
@PaulStoffregen 

Thanks for pointing that out.. considering it has "soft" as a part of the name I should have figured, no idea what I was thinking last night!

@cltnschlosser 
Yes, it seems that chip only has 8-bit timers.

**Comment by ArminJo** [comment]
IRremote and [IRMP ](https://github.com/ukw100/IRMP) now supports ATtinies and Digispark.
