### ISSUE TITLE
signed or unsigned value

### ISSUE THREAD

**Issue by ram-0000** [z3t0/Arduino-IRremote#232]
In file IRrecv.cpp, my compiler is warning

...\Arduino\libraries\IRremote\irRecv.cpp:197:2: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
  long  hash = FNV_BASIS_32;
  ^

Forcing FNV_BASIS_32 to unsigned seems to fix the problem

line 193 : #define FNV_BASIS_32 2166136261u

**Comment by z3t0** [comment]
Which version of the IDE?

**Comment by ram-0000** [comment]
Arduino 1.6.5 (the last one I suppose)

**Comment by ram-0000** [comment]
In Menu File / Settings, the compiler warnings level is set to "All" (which is not the default setting)

**Comment by z3t0** [comment]
I dont think it needs to be changed, its simply warning that it would not be unsigned if we were not using ISO C90:

https://github.com/sudar/Arduino-Makefile/issues/376
second post

**Comment by ram-0000** [comment]
As you wih

But I hate warning that may hide potential bugs or other important error message (difficult to see an error line among thousand lines or warning)

**Comment by z3t0** [comment]
Hmm I see, I'll reopen this as a reminder to look for something to make the warning disappear (if that is possble)

**Comment by z3t0** [comment]
Oh, it seems the solution is provided in your OP

**Comment by ram-0000** [comment]
Yes, a solution is provided free of charge !!!

**Comment by ArminJo** [comment]
Can not reproduce the warning anymore.
