### ISSUE TITLE
Wrong raw decode

### ISSUE THREAD

**Issue by lettierimarco** [z3t0/Arduino-IRremote#234]
After decode i see my mark/space buffer different from real.
For example

NEC 20DFC03F

REAL CODE:
MARK and SPACES in hex
2328 1194 230 230 230 230 230 69A 230 230 230 230 230 230 230 230 230 230 230 69A 230 69A 230 230 230 69A 230 69A 230 69A 230 69A 230 69A 230 69A 230 69A 230 230 230 230 230 230 230 230 230 230 230 230 230 230 230 230 230 69A 230 69A 230 69A 230 69A 230 69A 230 69A 230 0 

READ CODE:

22C4 11C6 1C2 28A 1F4 258 1F4 6D6 1F4 258 1F4 258 1F4 28A 1C2 28A 1F4 258 1F4 6D6 1F4 6A4 1F4 28A 1C2 6D6 1F4 6D6 1F4 6A4 1F4 6D6 1F4 6A4 1F4 6D6 1F4 6D6 1F4 258 1F4 258 1F4 258 1F4 28A 1F4 258 1F4 258 1F4 28A 1F4 258 1F4 6A4 1F4 6D6 1F4 6D6 1F4 6A4 1F4 6D6 1F4 6A4 1F4 0

Resending the read code i've to be really close to TV to work properly

**Comment by AnalysIR** [comment]
That is normal. Use the real values if you can.

IR receivers always distort the timings sometimes up to +/- 200 uSecs

By default, IRremote records with an accuracy of +/- 50uSecs on top of any distortion.

**Comment by AnalysIR** [comment]
of course it could also be related to you sending circuitry

**Comment by lettierimarco** [comment]
i've solved tuning TOLERANCE and MARK_EXCESS
