### ISSUE TITLE
Help RAW with Arduino Mega for air conditioning

### ISSUE THREAD

**Issue by carlosD2884** [z3t0/Arduino-IRremote#239]
goodnight beforehand I apologize for my English because it is very bad

I am doing my job as part of the degree , I control the air conditioning right through the Arduino using an IR LED

I have an Arduino MEGA
I'm using the pin 12 for pin reception
and modify the library to use the pin 11 for the IR LED
and modify the RAWPUF 250

I was able to receive and send nec encoding TV and air conditioning
I have a problem with an air whose encoding is Samsung with RAWPUF [100 ]

by pressing B modified frequency from 36kHz  to 40 KHz
C key to modify the length of the chain from take two elements to add two elements

with the keys 1,2,3 sending the previously stored frame with the first value to be deleted without the first value and not the start bit of the code SAMSUNG

attached the code I'm using , if they have any recommendations would appreciate it immensely

#include <Wire.h> 
#include <LiquidCrystal_I2C.h>
#include <Keypad.h>
#include <IRremote.h>

LiquidCrystal_I2C lcd(0x27,20,4);  // set the LCD address to 0x27 for a 16 chars and 2 line display
const byte ROWS = 4;
const byte COLS = 4;
char hexaKeys[ROWS][COLS] = {
  {'1','2','3','A'},
  {'4','5','6','B'},
  {'7','8','9','C'},
  {'*','0','#','D'}};  
byte rowPins[ROWS] = {22, 24, 26, 28};
byte colPins[COLS] = {23, 25, 27, 29}; 
Keypad customKeypad = Keypad( makeKeymap(hexaKeys), rowPins, colPins, ROWS, COLS );  

int RECV_PIN = 12;
IRrecv irrecv(RECV_PIN);
IRsend irsend;

decode_results results;
int khz = 38; // 38kHz carrier frequency for the NEC protocol
unsigned int irSignal1[] = {44418,4400,4400,500,1650,500,600,500,1650,500,1700,500,550,500,600,500,1650,500,600,500,600,500,1650,500,600,500,600,500,1650,500,1650,500,600,500,1650,500,1650,500,600,500,1650,500,1700,500,1650,500,1650,500,1700,500,1650,500,600,500,1650,500,600,500,550,500,600,500,600,500,600,500,550,500,600,500,600,500,550,550,550,500,600,500,600,500,550,500,600,500,1650,500,1700,500,1650,500,1650,500,1700,500,1650,500,1650,500,1650,500};
unsigned int irSignal2[] = {4400,4400,500,1650,500,600,500,1650,500,1700,500,550,500,600,500,1650,500,600,500,600,500,1650,500,600,500,600,500,1650,500,1650,500,600,500,1650,500,1650,500,600,500,1650,500,1700,500,1650,500,1650,500,1700,500,1650,500,600,500,1650,500,600,500,550,500,600,500,600,500,600,500,550,500,600,500,600,500,550,550,550,500,600,500,600,500,550,500,600,500,1650,500,1700,500,1650,500,1650,500,1700,500,1650,500,1650,500,1650,500};
unsigned int irSignal3[] = {560,1690,560,560,560,1690,560,1690,560,560,560,560,560,1690,560,560,560,560,560,1690,560,560,560,560,560,1690,560,1690,560,560,560,1690,560,1690,560,560,560,1690,560,1690,560,1690,560,1690,560,1690,560,1650,560,560,560,1690,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,560,1690,560,1690,560,1690,560,1690,560,1690,560,1690,560,1650,560,1690,500};
unsigned int rawCodes[RAWBUF]; // The durations if raw
int codeLen,Len1=2,Len2=2,Len3=2; // The length of the code

/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
void setup()
{
  Serial.begin(19200);
  
  lcd.begin(); 
  lcd.backlight();
  lcd.setCursor(0,0);
  lcd.print("lectura de control remoto");
}
////////////////////////////////////////////////////////
////////////////////////////////////////////////////////
void dump(decode_results *results) 
{
  int count = results->rawlen;
  codeLen = results->rawlen - 1;
  switch (results->decode_type) {
    default:
    case UNKNOWN:      Serial.print("UNKNOWN ");       break ;
    case NEC:          Serial.print("NEC ");           break ;
    case SONY:         Serial.print("SONY ");          break ;
    case RC5:          Serial.print("RC5 ");           break ;
    case RC6:          Serial.print("RC6 ");           break ;
    case DISH:         Serial.print("DISH ");          break ;
    case SHARP:        Serial.print("SHARP ");         break ;
    case JVC:          Serial.print("JVC ");           break ;
    case SANYO:        Serial.print("SANYO ");         break ;
    case MITSUBISHI:   Serial.print("MITSUBISHI ");    break ;
    case SAMSUNG:      Serial.print("SAMSUNG ");       break ;
    case LG:           Serial.print("LG ");            break ;
    case WHYNTER:      Serial.print("WHYNTER ");       break ;
    case AIWA_RC_T501: Serial.print("AIWA_RC_T501 ");  break ;
    case PANASONIC:    Serial.print("PANASONIC ");     break ;
    case DENON:        Serial.print("Denon ");         break ;
  }
  Serial.print(results->value, HEX);
  Serial.print("  o  ");
  Serial.print(results->value, BIN);
  Serial.print(" (");
  Serial.print(results->bits, DEC);
  Serial.println(" bits)");
  Serial.print("Raw (");
  Serial.print(count, DEC);
  Serial.print("): ");
 for (int i = 1; i <= codeLen; i++) {
      if (i % 2) {
        // Mark
        rawCodes[i - 1] = results->rawbuf[i]*USECPERTICK - MARK_EXCESS;
      } 
      else {
        // Space
        rawCodes[i - 1] = results->rawbuf[i]*USECPERTICK + MARK_EXCESS;
      }
      Serial.print(rawCodes[i - 1], DEC);
      Serial.print(",");
}
    Serial.println("");
}
////////////////////////////////////////////////////////
////////////////////////////////////////////////////////
void panellocal()
{   int ww=0;
  char customKey = customKeypad.getKey();
  if (customKey != NO_KEY)
  {
    switch (customKey)
    {
      case 'A': irrecv.enableIRIn(); // Start the receiver
                Serial.println("recibiendo");
     break;     
     //la rutina esta diseñada entre 36 y 40 kHZ      
     case 'B':  khz=36;
                irsend.sendSAMSUNG(0x24d1, codeLen);
                irsend.sendRaw(rawCodes, codeLen, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
                delay(1000);
                khz=37;
                irsend.sendRaw(rawCodes, codeLen, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
                delay(1000);
                khz=38;
                irsend.sendRaw(rawCodes, codeLen, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
                delay(1000);
                khz=39;
                irsend.sendRaw(rawCodes, codeLen, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
                delay(1000);
                khz=40;
                irsend.sendRaw(rawCodes, codeLen, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
      break;
     case 'C':  
                khz=38;
                Serial.print("codeLen-2");
                irsend.sendRaw(rawCodes, codeLen-2, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen-2);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
                Serial.print("codeLen-1");
                irsend.sendRaw(rawCodes, codeLen-1, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen-1);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
                Serial.print("codeLen");
                irsend.sendRaw(rawCodes, codeLen, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
                Serial.print("codeLen+1");
                irsend.sendRaw(rawCodes, codeLen+1, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen+1);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
                Serial.print("codeLen+2");
                irsend.sendRaw(rawCodes, codeLen+2, khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando raw");
                Serial.print("largo de la cadena: ");
                Serial.print(codeLen+2);
                Serial.print(" frecuencia: ");
                Serial.println(khz);
      break;
      case '1': 
                khz=38;
                irsend.sendRaw(irSignal1, sizeof(irSignal1) / sizeof(irSignal1[0]), khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando irSignal 1");
                Serial.print("largo de la cadena: ");
                Serial.print(sizeof(irSignal1)/ sizeof(irSignal1[0]) ); //sizeof(irSignal1)/ sizeof(irSignal1[0])
                Serial.print(" frecuencia: ");
                Serial.println(khz);
      break;
      case '2': 
                khz=38;
                irsend.sendRaw(irSignal2, sizeof(irSignal2) / sizeof(irSignal2[0]), khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando irSignal 2");
                Serial.print("largo de la cadena: ");
                Serial.print(sizeof(irSignal2)/ sizeof(irSignal2[0]));
                Serial.print(" frecuencia: ");
                Serial.println(khz);
      break;
      case '3': 
                khz=38;
                irsend.sendRaw(irSignal3, sizeof(irSignal3) / sizeof(irSignal3[0]), khz); //Note the approach used to automatically calculate the size of the array.               
                Serial.println("");
                Serial.println("enviando irSignal 3");
                Serial.print("largo de la cadena: ");
                Serial.print(sizeof(irSignal3)/ sizeof(irSignal3[0]));
                Serial.print(" frecuencia: ");
                Serial.println(khz);
      break;
      default:Serial.println("no pulso nada"); 
      break;   
    }
  }
}
////////////////////////////////////////////////////////
////////////////////////////////////////////////////////
void loop()
{
  if (irrecv.decode(&results)) 
  {
    //Serial.println(results.value, HEX);
    dump(&results);
    irrecv.resume(); // Receive the next value
  }    
panellocal();
}

/*
 * 
 * ..................................................................
aire cuarto de mi papa

Decoded NEC: 8166817E (32 bits)

Raw (68): 6430,8950,4450,550,1650,550,550,550,550,550,550,550,550,550,550,550,550,550,1650,550,550,550,1650,550,1700,500,600,500,600,500,1700,500,1700,550,550,550,1700,500,600,500,550,550,550,550,550,550,550,500,600,500,1750,500,550,550,1700,500,1700,500,1700,550,1700,500,1700,500,1750,500,550,550
..................................................................
tv cuarto de mi papa

Decoded NEC: 20DFC03F (32 bits)

Raw (68): 2232,9000,-4500,550,-550,550,-550,600,-1650,550,-600,550,-550,550,-550,600,-550,550,-550,550,-1700,550,-1700,550,-550,550,-1700,550,-1700,550,-1700,550,-1700,550,-1650,550,-1700,550,-1700,550,-550,550,-600,550,-550,550,-600,550,-550,550,-550,600,-550,550,-550,550,-1700,550,-1700,550,-1700,550,-1650,600,-1650,550,-1700,550
..................................................................
aire del spa
Decoded NEC: C3EAD798 (32 bits)
Raw (100): 18334,8850,-4500,550,-1700,550,-1700,600,-550,550,-550,550,-550,600,-550,550,-1700,550,-1700,600,-1650,600,-1700,550,-1700,600,-500,600,-1700,550,-550,600,-1650,600,-500,600,-1700,550,-1700,600,-500,600,-1650,600,-550,550,-1700,550,-1700,600,-1700,550,-1700,600,-500,600,-550,550,-1700,550,-1700,600,-500,600,-550,600,-500,600,-500,600,-550,600,-500,600,-550,550,-550,550,-1700,600,-500,600,-1700,550,-550,600,-550,550,-550,600,-500,600,-550,550,-550,550,-550,600,-550,550,
..................................................................
aire sala papa
88C0051 (28 bits)
Raw (60): -28940 8450 -4250 500 -1600 550 -550 550 -550 550 -500 550 -1650 500 -550 550 -550 550 -550 500 -1650 550 -1600 550 -550 550 -500 550 -550 550 -550 550 -500 550 -550 550 -500 600 -500 550 -550 550 -550 500 -550 550 -1650 500 -550 550 -1600 550 -550 550 -550 550 -500 550 -1600 550 
...................................................................
tv sala papa
E0E040BF (32 bits)
Raw (68): -18312 4500 -4500 500 -1700 550 -1650 550 -1650 600 -550 550 -550 550 -550 550 -550 550 -600 500 -1700 550 -1650 550 -1650 550 -600 550 -550 550 -550 550 -550 550 -550 550 -550 550 -1700 550 -550 550 -550 550 -550 550 -550 550 -600 550 -550 550 -1650 550 -550 550 -1700 550 -1650 550 -1650 550 -1700 550 -1650 550 -1650 550 
..................................................................
tv mi cuarto
71F9F1D7
Unknown encoding: 71F9F1D7 (32 bits)
Raw (38): 17290,8250,-4200,450,-550,500,-550,500,-1550,500,-550,500,-1550,500,-550,500,-500,500,-550,500,-4100,550,-1550,500,-500,550,-1550,500,-500,550,-1500,550,-500,550,-500,500,-550,500,
..................................................................
rv cuerto de mi mama
20DF10EF
Decoded NEC: 20DF10EF (32 bits)
Raw (68): 24268,9050,-4400,650,-500,600,-500,650,-1600,650,-500,600,-500,650,-500,600,-500,650,-500,600,-1650,600,-1650,600,-500,650,-1600,650,-1600,650,-1600,650,-1600,650,-1600,650,-450,650,-500,600,-500,650,-1600,650,-500,600,-500,650,-500,600,-500,650,-1600,650,-1600,650,-1600,650,-500,600,-1650,600,-1650,600,-1650,600,-1650,600,
.................................................................

The .txt file is the .ino

[controlremoto5.2.txt](https://github.com/z3t0/Arduino-IRremote/files/45332/controlremoto5.2.txt)

**Comment by carlosD2884** [comment]
The .txt file is the .ino

**Comment by AnalysIR** [comment]
RAWBUF should be increased from 100 to handle longer signals. The maximum sizze is 255 (so it will not work for many AC signals.

...or use 
http://www.analysir.com/blog/2014/03/19/air-conditioners-problems-recording-long-infrared-remote-control-signals-arduino/

the following may be useful
http://www.analysir.com/blog/tag/air-conditioner/
http://www.analysir.com/blog/tag/aircon/

**Comment by carlosD2884** [comment]
the problem is that the AC in my house has a length of 212 and worked well , but this has AC SAMSUNG code length is 100 and not respond at all

**Comment by AnalysIR** [comment]
use the sketch in the first link to capture the signal, it is more accurate than irremote

**Comment by carlosD2884** [comment]
good morning , and achieve receive and transmit the signal to go diferenes acondicinados air .

The problem that I had was the samsung for air conditioning signal should be sent twice with a pause between a sign and another 4900us .

finding : My recommendation is to continue to use the library as IRremote.h is complete only must modify RAWPUF 250

**Comment by AnalysIR** [comment]
Good news :)

Why not post a few signals that worked for you.

**Comment by carlosD2884** [comment]
signal sent by the remote coding samsung

![control1](https://cloud.githubusercontent.com/assets/16039739/11507943/99aa8110-9828-11e5-8357-b723b039f67e.jpg) 

signal reproduced by the Arduino
![arduino2](https://cloud.githubusercontent.com/assets/16039739/11507944/99b6650c-9828-11e5-92b2-10a6328a8a12.jpg) signal reproduced by the Arduino

comparison of the two signals to be followed reporducidas 2 times
![sin titulo](https://cloud.githubusercontent.com/assets/16039739/11508097/29c7b984-9829-11e5-8969-68e9650155c6.png)

**Comment by z3t0** [comment]
Seems to be resolved.

**Comment by nblrehman** [comment]
@carlosD2884    Could you please tell me the source where you came to know about the (4900) misroseconds delay... please.. Thankyou.

**Comment by AnalysIR** [comment]
Judging from the traces  posted earlier...it looks like there is a 4979 gap between the signals

There also seems to be a 2500 there as well, but that could be just an artefact of the LA usage.

However as all the signal parts seem to have this 4979 gap **exactly**, it may be questionable???
