### ISSUE TITLE
irRecv.cpp errors

### ISSUE THREAD

**Issue by photobrain1** [z3t0/Arduino-IRremote#250]
I consistently generate compile errors with the library. I am using Energia for Launchpad.  The code is quite simple:

#include <IRremote.h>

IRsend irsend;

void setup()
{
Serial.begin(9600);
}

void loop() {
if (Serial.read() != -1) {
for (int i = 0; i < 3; i++) {
irsend.sendNEC(0x20DFDF20, 32); //Send EZ Adjust
delay(100);
}
}
}

However the errors generated (either on TI cloud based Energia or the one on my Mac are:

/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp: In member function 'void IRrecv::enableIRIn()':
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:115:6: error: 'cli' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:120:2: error: 'TCCR2A' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:120:2: error: 'WGM21' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:120:2: error: '_BV' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:120:2: error: 'TCCR2B' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:120:2: error: 'CS21' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:120:2: error: 'OCR2A' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:120:2: error: 'TCNT2' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:123:2: error: 'TIMSK2' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:123:2: error: 'OCIE2A' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:123:2: error: '_BV' was not declared in this scope
/Applications/Energia.app/Contents/Resources/Java/hardware/msp430/libraries/IRremote/irRecv.cpp:127:6: error: 'sei' was not declared in this scope

Please help.

**Comment by AnalysIR** [comment]
AFAIK the LaunchPad and other MSP devices are not supported by this version of the library.

You might/should  find another version of IRremote that has been ported to the TI & Energia platform via Google

**Comment by photobrain1** [comment]
Ironically I have tried even the version approved for the LaunchPad and it still throws the same errors.  It seems to be a problem with the header file, however, I can't seem to track down the proper declarations.

**Comment by AnalysIR** [comment]
if it throws the same errors it isnt for the launchpad....as those errors are Atmel/AVR related.

You should confirm that the library version you are using, supports the platform you are using.

Sometimes the IDEs need to be restarted before a newly installed  library will be used correctly.

**Comment by z3t0** [comment]
Can you provide a link to the ported library?

**Comment by photobrain1** [comment]
http://energia.nu/downloads/downloadv3.php?file=energia-0101E0017-macosx-signed.dmg  It is located in the executable under "Contents/Resources/Java/hardware/msp430/libraries"  From what it looks like it is Ken's 1.0 distro of the arduino library.

**Comment by z3t0** [comment]
What board are you using? and https://github.com/energia/Energia/blob/master/hardware/msp430/libraries/IRremote/IRremoteInt.h seems quite old indeed

**Comment by photobrain1** [comment]
msp430g2.  I am concentrating on IRremoteInt.h right now.

**Comment by z3t0** [comment]
seems that its possible (https://www.youtube.com/watch?v=xhDQqxPzLjc)

https://hackaday.com/2015/06/19/ir-remote-for-smartphone-via-bluetooth-adapter/#more-159421

**Comment by z3t0** [comment]
Closed for inactivity
