### ISSUE TITLE
IR SEND (DECODE)

### ISSUE THREAD

**Issue by EscuderoKevin** [z3t0/Arduino-IRremote#255]
Hi good afternoon, I make a query as to convert the value that gives me this:

#include <IRremote.h>

const int RECV_PIN = 6;

IRrecv irrecv(RECV_PIN);

decode_results results;

void setup()
{
  Serial.begin(9600);
  irrecv.enableIRIn(); // Start the receiver
  irrecv.blink13(true);
}

void loop() {
  if (irrecv.decode(&results)) {
    if (results.decode_type == NEC) {
      Serial.print("NEC: ");
    } else if (results.decode_type == SONY) {
      Serial.print("SONY: ");
    } else if (results.decode_type == RC5) {
      Serial.print("RC5: ");
    } else if (results.decode_type == RC6) {
      Serial.print("RC6: ");
    } else if (results.decode_type == UNKNOWN) {
      Serial.print("UNKNOWN: ");
    }
    Serial.println(results.value, HEX);
    irrecv.resume(); // Receive the next value
  }
}
The Value is

NEC: 188008 OFF
NEC: 10188008 ON
A value that I have to send in the irsend.NEC (0x68B92, 20); ??

Thank you.

**Comment by EscuderoKevin** [comment]
This value "irsend.NEC (0x68B92, 20)" How to get it ?

**Comment by z3t0** [comment]
As a base 10 number? or binary?
as binary: 0b1101000101110010010

On Sun, Jan 10, 2016 at 3:54 PM, EscuderoKevin <notifications@github.com>
wrote:

> This value "irsend.NEC (0x68B92, 20)" How to get it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/z3t0/Arduino-IRremote/issues/255#issuecomment-170397614>
> .
>



-- 
Thanks,
Rafi Khan

**Comment by AnalysIR** [comment]
Assuming the values you posted are HEX then try the following:
````
irsend.NEC (0x188008, 32);
delay(5000);
irsend.NEC (0x10188008, 32);
delay(5000);
````
or if they were decimal try
````
irsend.NEC (188008, 32);
delay(5000);
irsend.NEC (10188008, 32);
delay(5000);
````
NEC protocols are nearly always 32 bits long

**Comment by z3t0** [comment]
Closed for inactivity
