### ISSUE TITLE
user customisable  MARK_EXCESS

### ISSUE THREAD

**Issue by pandacriss** [z3t0/Arduino-IRremote#265]
thansk to AircraftGuy i find that my problem was the  MARK_EXCESS was too long for my setup.
it would be a good idea to make it user customizable at any given point with
irrecv.Mark_Excess_Adj(100)
or at least at the constructor IRrecv irrecv(RECV_PIN, MARK_EXCESS_TIME)

also may be you should recommend adding low pass filter to the IR power line.   
im using a 220 Ohm and a 104 ceramic cap in the power line of a TSOP1838
thanks for the project guys

**Comment by z3t0** [comment]
Yes see #266
