### ISSUE TITLE
JVC and LG are virtually identical

### ISSUE THREAD

**Issue by adamlhumphreys** [z3t0/Arduino-IRremote#284]
**Board:** ARDUINO UNO
**Library Version:** 2.1.0
**Protocol:** JVC and LG

Looking at both protocols, while the code is visually different, the protocols are virtually identical with small exceptions. One difference is the bit count. JVC decode would run successfully for LG since it's listed before LG, but would return the wrong number in results->bits. The other difference is JVC looks for a repeat.

Otherwise, these two protocols could be combined into one .cpp while preserving separate decode and send functions for legacy code and saving program space. (i.e. sendLG would just call sendJVC, decodeLG would check bits then call decodeJVC which would return the actual bits read.)

Official documentation would of course be insightful. I actually have a fairly new LG window AC unit with remote control, but it uses the NEC protocol.

**Comment by z3t0** [comment]
It seems we need to work on figuring out where all of these implementations are coming from and then find a "trustworthy" source to work from which we can then also cite as a source.

#331 #333
