### ISSUE TITLE
scuza i want to know how i can install library RobotIRremote because its always giving me error for statues 1

### ISSUE THREAD

**Issue by usama93** [z3t0/Arduino-IRremote#287]
**Board:** ARDUINO UNO
**Library Version:** 2.1.0
**Protocol:** Sony (if any)

**Code Block:**
```c

#include <IRremote.h> 

.....

```

Use [a gist](gist.github.com) if the code exceeds 30 lines

**checklist:**
- [] The latest [release](https://github.com/z3t0/Arduino-IRremote/releases/latest) is used
- [] Any code referenced is provided
- [] The title of the issue is helpful and relevant 

The above is a short template allowing you to make detailed issues!

**Comment by z3t0** [comment]
Please Delete the RobotIRremote library, make sure you are using the latest library version
