### ISSUE TITLE
Which pins should i use on microduino core+ (Avoiding any tx/rx pin)

### ISSUE THREAD

**Issue by dmsherazi** [z3t0/Arduino-IRremote#307]
**Board:** Microduino Core+
**Library Version:** 2.1.0

I am using [microduino core + ](https://wiki.microduino.cc/index.php?title=Microduino-Core
) and I am already using both the uarts. Which pins I can use for sending. 

Also I am a bit confused regarding pin3? is it the pin3 the PD3 on avr?

**Comment by AnalysIR** [comment]
For the Atmega644P variant the library defaults to pin D14 for IR Tx. If you have the Atmega1284P variant, it is not defined in the library, at present,

If you are lucky, the defaults may output on D14 for both variants???

**Comment by dmsherazi** [comment]
Thanks alot @AnalysIR ..

I would try this

**Comment by dmsherazi** [comment]
I am having an issue I am trying the [LGACSendDemo.ino](https://github.com/z3t0/Arduino-IRremote/blob/3aebf42ca8daa865ce8ae572245328e7443e438e/examples/LGACSendDemo/LGACSendDemo.ino) .

When I observe the IR Led via a camera its ON all the time. I have connected it so that it sinks to the microcontroller ( **cathode **connected to processor while **anode **connected to **VCC**).

**Comment by dmsherazi** [comment]
@AnalysIR  is this the correct connection?? https://camo.githubusercontent.com/cfcb72faa33d7f812e8496000bb62b09b6da9b76/687474703a2f2f617263666e2e636f6d2f696d616765732f69722d736368656d617469632e706e67

**Comment by AnalysIR** [comment]
That looks fine for a standard Arduino. (eg UNO)

However, your Tx pin may be different as already discussed above.
Presumably you have defined pin 11 as the IR receive pin.

Regarding the IR receiver pinout...it looks fine, but as you have not stated the model number, it is not possible to confirm this. Different receivers will have different pinouts.

**Comment by dmsherazi** [comment]
@AnalysIR  yes, basically I wanted to verify the direction of the sensor and tx led. For Tx Led is there any specifications? or just a standard IR led would be OK?

**Comment by AnalysIR** [comment]
Yes a standard IR LED for remote control is fine. Make sure it is 944 nm (not 850nm). We use TSAL6100, TSAL6200 or TSAL6400.

The wiring above  for the LED is good. The longer lead is +ve and the shorter lead goes to GND.

**Comment by dmsherazi** [comment]
@AnalysIR  great.. so I can take one from an old tv remote! :)

**Comment by AnalysIR** [comment]
Yes - perfectly fine, but you will have to figure out which pin is -ve etc.

(Trace it back to the -ve terminal on the battery)

**Comment by dmsherazi** [comment]
Yup.. Thanks alot @AnalysIR
