### ISSUE TITLE
Arduino IRremote error

### ISSUE THREAD

**Issue by MCButterMonster** [z3t0/Arduino-IRremote#317]
I was compiling some code for my Arduino "smart car robot" and this error showed up when uploading,

C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremoteTools.cpp:5:16: error: 'TKD2' was not declared in this scope

 int RECV_PIN = TKD2; // the pin the IR receiver is connected to

                ^

exit status 1
Error compiling for board Arduino/Genuino Uno.

Here is my code,
[http://pastebin.com/Dvb7EmvF](url)

Thanks!

**Comment by AnalysIR** [comment]
see point #5 in the readme for this library

[https://github.com/z3t0/Arduino-IRremote/blob/master/README.md](url)

**Comment by MCButterMonster** [comment]
How do I delete that?

**Comment by z3t0** [comment]
What operating system are you using

**Comment by z3t0** [comment]
Never mind. Just find the folder in your original post and delete that.
