### ISSUE TITLE
IRremote with ATtiny2313 using arduino uno

### ISSUE THREAD

**Issue by harishshankar** [z3t0/Arduino-IRremote#322]
**Board:** ATTiny2313

i got this error when i upload IRremote program to ATtiny2313 .
can anyone fix this error 
thank you.

[error](https://gist.github.com/z3t0/91ca4761e6a271aabfa579561f1ca756)

EDIT: changed boardname and used gist for error log :wink: (by z3t0)

**Comment by AnalysIR** [comment]
Hi 
It appears the ATtiny2313 is not a supported platform for this library.

However, your error looks like it is related to Timer2 and I suspect the ATtiny2313 does not have a Timer 2. (?)

One possible approach would be to change the default timer to Timer1 from Timer2. You will just need to change the deafult setting around lines 206 & 207 of IRremoteInt.h.

So comment the line for Timer2 and uncomment the line for Timer1 after the #else 

There is no guarantee this will work, but it is the best approach. If not, search for any fork of IRremote that may support this MCU.

**Comment by z3t0** [comment]
@harishshankar This board is currently unsupported. We are currently in the process of adding support for a number of boards so we are unavailable to work on adding support for this particular board, however you are free to work on it and let us know via a PR if you get anywhere.

If you do decide to try and add support yourself, feel free to create an issue to keep track of your progress while also being able to ask the community questions if you hit any walls.
