### ISSUE TITLE
ATTiny 85 @ 1MHz

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#332]
**Board:** ATTiny85
**Library Version:** 2.1.0
**Protocol:** N/A

This issue is to note that support fot ATTiny85 @ 1MHz is currently not working and is being worked on as a request from a community member.

**Comment by sid1202** [comment]
I was having issues with my IR/AtTiny project because of this. I'm happy that it is being worked on already :)

Sid
