### ISSUE TITLE
Problem memory for IR VS1838B

### ISSUE THREAD

**Issue by gnunicky** [z3t0/Arduino-IRremote#338]
**Board:** ARDUINO YUN or LEONARDO
**Library Version:** 2.1.0
I'm using the IR Receiverr VS1838B and Remote Controller Car mp3, see:
[Decode Infrared Remote Controller with IR Receiver VS1838B](http://osoyoo.com/2014/12/08/decode-infrared-remote-controller-with-ir-receiver-vs1838b/)
The [library ](https://github.com/z3t0/Arduino-IRremote) perfectly works, but it uses lots of memory, around 44% in the below example.
Could you please suggest as a possible way to minimize the use of memory on our Arduino?
Thank you for your work and your help.

``` c
/*
 * IRremote: IRrecvDemo - demonstrates receiving IR codes with IRrecv
 * An IR detector/demodulator must be connected to the input RECV_PIN.
 * Version 0.1 July, 2009
 * Copyright 2009 Ken Shirriff
 * http://arcfn.com
 */

#include <IRremote.h>
int RECV_PIN =11;
IRrecv irrecv(RECV_PIN);
decode_results results;

void setup()
{
  Serial.begin(9600);
  irrecv.enableIRIn(); // Start the receiver
}

void loop() {
  if (irrecv.decode(&results)) {
    Serial.println(results.value, HEX);
    irrecv.resume(); // Receive the next value
  }
  delay(100);
}

```

**Comment by z3t0** [comment]
You can go into the files and remove the defines that are not being used.
