### ISSUE TITLE
RedBearLab BLE Nano

### ISSUE THREAD

**Issue by llemtt** [z3t0/Arduino-IRremote#346]
Has anyone tried to support the BLE Nano?

It's based on Nordic nRF51822 (ARM Cortex-M0).

**Comment by z3t0** [comment]
Not that i know of, you may want to look into the code for teensy as I believe one of them (LC?) uses a Cortex M0. And then with a little bit of expertise it should be fairly trivial to add support for the requested micro controller.

**Comment by BandonRandon** [comment]
seems #318 is a duplicate (with more comments) regarding M0 support.

**Comment by llemtt** [comment]
As written in #318 M0 is the name of the "core" (think CPU) of the MCU/SOC, all the peripherals (TIMERS..) are different from family to family. AVRs, STM32s, nRF51s,... each one requires a different implementation.

Anyway I managed to have some working code on the BLE Nano but since then I discovered my HVAC has also a serial port..

**Comment by ArminJo** [comment]
[IRMP ](https://github.com/ukw100/IRMP)has mbed (Nano 33 BLE) support.
