### ISSUE TITLE
IRremote library for arduino mkr1000

### ISSUE THREAD

**Issue by codehArt** [z3t0/Arduino-IRremote#349]
**Board:** ARDUINO MKR1000
**Library Version:** 2.0.1
**Protocol:** Generic send

**Code Block:**

can you add support for arduino mkr 1000 for this library,
 however, I tried to upload your sketch but it is giving me an error like ( **only for arduino mkr1000**)

> **Error**
error: expected constructor, destructor, or type conversion before '(' token
 ISR (TIMER_INTR_NAME)
     `^`
Multiple libraries were found for "IRremote.h"
 Used: C:\Users\user1\Documents\Arduino\libraries\IRremote
 Not used: C:\Program Files (x86)\Arduino\libraries\RobotIRremote
exit status 1

looking for further help

**Comment by z3t0** [comment]
Please see #318 

Closes as this is a duplicate
