### ISSUE TITLE
Difference of pressing IRremote button for a long time or a shor time 

### ISSUE THREAD

**Issue by liang-jia** [z3t0/Arduino-IRremote#359]
**Board:** ARDUINO UNO
**Library Version:** 2.1.0
**Protocol:** Sony (if any)

HI,
 I have a problem  that the learning device sometimes can't succede learning when I press the IRremote button for a long time or a shor time ,can you tell me that it's diffrent for pressing long time or short ? Has the software some method to enhance the learning succeding rate for IRremote?

Thanks

**Comment by z3t0** [comment]
I am not certain about all remotes but I know for my generic remote which is recognized as NEC, sends FFFF for repeat keys. 

IRremote doesn't necessarily handle this as different protocols may use different methods to signal long press (I'm not too sure), but you could easily program this as a part of your sketch.

I would recommend loading up IRRecvDumpV2 and take a look at what your remote does when holding down buttons

**Comment by z3t0** [comment]
For example, the following is how the NEC works.
https://i.imgur.com/TcyNC24.png

The only way to determine how long it was pressed is to count up how many repeat signals are sent by the remote.

**Comment by bengtmartensson** [comment]
IrScrutinizer can be used; it identifies a repeating portion of an ir sequence, and counts the number of occurances (on the plot: intro: red, repeat: blue, ending (when present): green).
