### ISSUE TITLE
Add architectures to library.properties

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#364]
Once the Library Manager is released check for the supported architectures and add them to the library.properties file.

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

**Comment by z3t0** [comment]
Edit: The documentation is outdated and I just realized I have been using Library manager all along as it is a part of the IDE... Will look into the architectures if i can find some updated documentation

**Comment by ArminJo** [comment]
@z3t0 Hi Rafi, is this still an issue?
@bengtmartensson What is your opinion?
I can do it, but I do not want to decide it alone.

**Comment by bengtmartensson** [comment]
Currently, it is 

    architectures=*

which is simply not true: the library does not run on all architectures. So, it is still an issue.

Gleaning on Infrared4Arduino, it should probably start with 

    architectures=avr,megaavr,samd,sam,esp32

possibly with some additions (attiny?)

**Comment by ArminJo** [comment]
I changed it to avr,megaavr,samd,esp32,mbed, since sam (Arduino DUE is AFIK not supported).
