### ISSUE TITLE
Add AtTiny13

### ISSUE THREAD

**Issue by pogof** [z3t0/Arduino-IRremote#368]
Hello,
I found this library when I was working on automatic switch for my LED strip. It has IR reciever and remote controller so either I have to cut the power off or make automatic IR control. I was able to decode the IR signal and used it on my Arduino but that is total waste (and it is really big) for such small project. So I have ten AtTiny13 that I bought for other project off ebay for really good price (in fact cheaper then what cost one AtTiny85 in my local shop).
Pins are the same as for the AtTiny85 but when I tried to upload the code (I know that it is not in the supported devices, but who knows?), I got this error message:

> In file included from C:\Users\radek\Documents\Arduino\libraries\IRremote\IRremote.h:24:0,
> 
> ```
>              from C:\Users\radek\Documents\Arduino\libraries\IRremote\IRremote.cpp:25:
> ```
> 
> C:\Users\radek\Documents\Arduino\libraries\IRremote\IRremote.cpp: In function 'void TIMER2_COMPA_vect()':
> 
> C:\Users\radek\Documents\Arduino\libraries\IRremote\IRremoteInt.h:92:35: error: 'B00100000' was not declared in this scope
> 
>   #define BLINKLED_ON()  (PORTB |= B00100000)
> 
> ```
>                                ^
> ```
> 
> C:\Users\radek\Documents\Arduino\libraries\IRremote\IRremote.cpp:189:10: note: in expansion of macro 'BLINKLED_ON'
> 
> ```
>  else BLINKLED_ON() ;   // if no user defined LED pin, turn default LED pin for the hardware on
> 
>              ^
> ```
> 
> C:\Users\radek\Documents\Arduino\libraries\IRremote\IRremoteInt.h:93:36: error: 'B11011111' was not declared in this scope
> 
>  # define BLINKLED_OFF()  (PORTB &= B11011111)
> 
> ```
>                                 ^
> ```
> 
> C:\Users\radek\Documents\Arduino\libraries\IRremote\IRremote.cpp:191:10: note: in expansion of macro 'BLINKLED_OFF'
> 
> ```
>  else BLINKLED_OFF() ;   // if no user defined LED pin, turn default LED pin for the hardware on
> 
>       ^
> ```
> 
> Using library IRremote version 2.0.1 from: C:\Users\radek\Documents\Arduino\libraries\IRremote 
> exit status 1
> Error in compiling for dev board Attiny 13A standalone 1.2mhz.

(The three last lines are hand translated from czech)

I am using this "hardware core" as for the compiling.
https://sourceforge.net/projects/ard-core13/

Only thing I want to is send IR over NEC.

Thank you,
Filip AKA Pogof

**Comment by AnalysIR** [comment]
If you check the [README ](https://github.com/z3t0/Arduino-IRremote/blob/master/README.md)for the library, you will see a list of supported MCU platforms.

I suspect the reason the ATtiny is not supported is because it has only one Timer & IRremote needs a second Timer beyond the one used for the sytem clock - to generate the IR Carrier using PWM,

BTW: You can get Arduino Nano clones from AliExpress for circa $2 incl delivery.
