### ISSUE TITLE
Use of Library

### ISSUE THREAD

**Issue by MaxAtStar** [z3t0/Arduino-IRremote#429]
I didn't use the format as this is just a quick question, can I/you provide a download to an edited version of your library for download? I made a tutorial for sending IR codes with an Arduino to easily control multiple LED Strip arrays. I wanted to edit your code so this can be done, and done easily for the end user. Can I provide a download link to your library with my edits if I give credit? Anyways, thanks, I don't know another way to contact you...

**Comment by kenan-kajkus** [comment]
Quote drin readme: "Contact

Email: zetoslab@gmail.com Please only email me if it is more appropriate than creating an Issue / [...]"

**Comment by z3t0** [comment]
@MaxAtStar can't remember if I ever helped you out... do you still need anything?

**Comment by MaxAtStar** [comment]
You did, thanks
