### ISSUE TITLE
Unable to generate High Frequency PWM while using IRremote library

### ISSUE THREAD

**Issue by supernova432** [z3t0/Arduino-IRremote#430]
**Board:** ARDUINO UNO
**Library Version:** 2.1.0
**Protocol:** RC5

Hi, 

I am using IRremote library to decode RC5 signals and control duty cycle of high frequency PWM, but for some reason the IR receiver freezes whenever I try to generate high frequency PWM either from timer 1 or timer 0. Although normal PWM operations work fine using analogWrite() function. 

This is the code I have written, any help will be appreciated

**Code Block:**
```c
https://gist.github.com/supernova432/51f3912ebd9e56a56eab0b6b4d157495
```

Use [a gist](gist.github.com) if the code exceeds 30 lines

**checklist:**
- [] I have **read** the README.md file thoroughly
- [] I have searched existing issues to see if there is anything I have missed.
- [] The latest [release](https://github.com/z3t0/Arduino-IRremote/releases/latest) is used
- [] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here
- [] The title of the issue is helpful and relevant 

** We will start to close issues that do not follow these guidelines as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

The above is a short template allowing you to make detailed issues!

**Comment by AnalysIR** [comment]
Timer0 is used by the Arduino system
Timer1 is used by IRremote by default.

So you should use Timer2 or analogWrite for your PWM (not Timer1).

Alternatively, you can config IRremote to use Timer2 instead which would leave Timer1 free for your PWM.
