### ISSUE TITLE
Better testing

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#452]
Need some way to do more extensive testing

**Comment by z3t0** [comment]
look at http://docs.platformio.org/en/latest/plus/unit-testing.html

**Comment by bengtmartensson** [comment]
I have found it very useful to have the possibility to test certain parts (decoding and rendering or particular protocols for example) on the PC, without flashing it onto the board first. This is done in Infrared4Arduino, supported in the Makefiles there.

**Comment by z3t0** [comment]
Will follow up on #474
