### ISSUE TITLE
write a parser for keywords.txt

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#455]
far too annoying to have to change this file for every update. need a consistent api and autogenerator for this

**Comment by bengtmartensson** [comment]
Alternative 1: Who cares? Don't waste your time.

Alternative 2: Use Doxygen (cf. #461) to generate XML "documentation". Then write an XSLT-transformatioin that takes the XML documentation to keywords.txt. Should really not  take too long for someone who knows XSLT (there is at least one person around....)

**Comment by z3t0** [comment]
Perfect solution.

**Comment by bengtmartensson** [comment]
[Here](https://github.com/bengtmartensson/KeywordsTxtGenerator) is such a generator, constructed along the lines in "Alternative 2".

**Comment by ArminJo** [comment]
Nor really required, the keywords.txt is changing slowly (and who cares if its content is outdated?)
