### ISSUE TITLE
Memory footprint needs to be as small as possible.

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#459]
Goal: 500 Bytes

**Comment by z3t0** [comment]
Currently 9 bytes with an empty sketch using UNO

**Comment by AnalysIR** [comment]
Needs to specified in terms of both RAM & flash.

I presume this is for AVR328p arduino as a pseudo reference platform. (vs 32 bit platforms)

...which raises the issue...Whats good for 8-bit (low resource) isn't always ideal for 32-bit (lots more resources).

> Currently 444 bytes with an empty sketch using UNO

If the sketch is empty, the compiler may have dropped out most of the code?


You may be better referencing the size increase between a basic sketch using serial, millis, micros etc and some reference IRremote sketches (with/without Serial?)
- Rx, size for only decoding NEC.
- Tx, size for only sending NEC.
- Tx/Rx, size for sending & decoding NEC.

It could also serve as an ongoing baseline comparison for checking the impact of any future changes.
