### ISSUE TITLE
DecodeIR now available for (larger) Arduinos

### ISSUE THREAD

**Issue by bengtmartensson** [z3t0/Arduino-IRremote#465]
I apologize that this is not an issue in the strict sense. However, I do not know a really better option.

DecodeIR is a well known library for the decoding of IR signals.  It was written by John Fine, and is used as a shared library in several programs for Windows/Linux/Mac, including IrScrutinizer. It knows well over 100 protocols.

I have succeeded in porting it to the Arduino. ([Forum thread](http://www.hifi-remote.com/forums/viewtopic.php?t=100598)) However, due to its size it does not run on the "small" Arduinos (Uno, Nano, etc). Ir runs fine on Mega2560, and on the 32bit boards. It was just accepted into the Arduino library manager. It works well with IRremote, for example with the included example IRremoteDecode, listed below.

To install, just use the Arduino library manager to install "DecodeIR".

I just discovered an "const correctness" issue, and fixed it a the 2.45.1 version. It may take a few days before 2.45.1 is available in the library manager. If it bites you, and you can't wait, get the latest  from my [GitHub repository](https://github.com/bengtmartensson/Arduino-DecodeIR).

```#include <IRremote.h>
#include <decodePrintIr.h>

static const unsigned int RECV_PIN = 11;

static IRrecv irrecv(RECV_PIN);

static decode_results results;

void decode(decode_results* results) {
    unsigned int length = results->rawlen;
    microseconds_t buf[length];
    for (unsigned int i = 0; i < length - 1; i++) {
        buf[i] = USECPERTICK*results->rawbuf[i+1];
    }
    buf[length-1] = 65000U;
    
    decodePrintIr(Serial, buf, length/2);
}

void setup() {
    Serial.begin(115200);
    irrecv.enableIRIn(); // Start the receiver
}

void loop() {
    if (irrecv.decode(&results)) {
        decode(&results);
        irrecv.resume(); // Receive the next value
    }
}```

**Comment by ArminJo** [comment]
Added in the readme
