### ISSUE TITLE
When to support Arduino101

### ISSUE THREAD

**Issue by vyuke** [z3t0/Arduino-IRremote#478]
I tried using IRremote lib to receive IR signals in Arduino 101，but Arduino IDE prompt
 “ fatal error: avr/interrupt.h: No such file or directory
 #include <avr/interrupt.h>”
 when Compilation terminated
How can we solve this problem? Or when does IRremote lib support Arduino101 ?

![20170608144917](https://user-images.githubusercontent.com/18086671/26915710-b8a9d9da-4c59-11e7-8612-baa89063ba32.png)

**Comment by bengtmartensson** [comment]
I am not 100% sure, but you can try the fork of PR #437 instead of the main branch.

**Comment by z3t0** [comment]
Closing as it is not really an issue, the board is not officially supported by this library.

**Comment by mataide** [comment]
@z3t0 Missed to close

**Comment by z3t0** [comment]
@mataide thanks :smile:
