### ISSUE TITLE
Support for long codes

### ISSUE THREAD

**Issue by toffyrn** [z3t0/Arduino-IRremote#49]
I am trying to reverse engineer my heat pump's (Mitsubishi) remote control. The control seems to do large transmits, but strange things happens when increasing RAWBUF to 256 or beyond.

When having RAWBUF=254 the transmit starts with [34362,3350 1650,450 1200,450 ...].
Having RAWBUF=256 the transmit starts with [1200,450 350,450 450,400 ...].

It seems like the raw data no longer starts at the beginning of the transmit. I suspect that this is due to the code being repeated, and the IRremote picks up the middle part.

How do I proceed in debugging this?
#18 deg. Celsius (RAWBUF=254)

34362,3350 1650,450 1200,450 1200,500 350,450 400,450 350,450 1250,450 350,450 400,450 1200,450 1200,500 350,500 1150,500 350,450 400,450 1200,450 1200,500 350,450 1200,500 1200,450 400,400 400,450 1200,500 350,450 400,450 1200,450 400,450 350,500 350,450 350,500 350,500 350,450 400,450 350,450 400,450 400,450 350,500 350,450 400,400 400,500 350,450 400,450 350,450 400,450 400,450 350,450 1250,450 350,500 350,450 350,500 350,500 350,450 1200,450 400,450 400,450 350,450 400,450 350,500 1200,450 400,450 350,450 400,450 350,500 350,450 400,450 400,450 350,450 400,450 400,450 1200,450 1200,450 350,500 350,450 400,450 400,450 350,500 1200,450 1200,450 1200,450 1250,450 350,500 350,450 1200,450 1250,450 1200,450 1200,450 400,450 1200,450 350,500 400,450 350,450 400,450 400,450 350,450 350,500 400,450 350,450 400,450 400,450 350,450 400,400 450,450 350,450 400,450 400,450 350,450 400,450 400,450 1200,450 350,500 350,450 400,450 400,450 350,450 1250,400 400,450 400,450 1200,450 400,450 350,500 1150,500 350,500 350,450 350,500 350,450 400,450 
#18 deg. Celsius (RAWBUF=256)

1200,450 350,450 450,400 350,500 350,450 1250,400 400,450 400,450 400,450 350,450 1250,450 1200,450 1200,450 400,450 400,450 1200,450 400,450 350,450 350,500 1200,450 1200,500 350,450 400,450 1200,450 400,450 350,450 1250,450 350,500 400,400 400,450 400,400 400,450 350,500 350,500 350,450 400,500 300,500 350,450 400,450 350,450 400,450 400,450 350,500 350,450 400,450 350,500 350,450 1200,450 400,450 350,450 400,450 400,450 400,450 1200,450 400,400 400,450 400,450 400,450 350,500 1200,450 350,450 400,450 350,450 400,450 400,450 400,400 450,400 400,450 350,500 350,500 1150,500 1150,500 350,500 400,400 400,450 350,450 400,450 1200,500 1200,450 1200,450 1200,450 400,450 400,450 1200,450 1200,500 1200,450 1200,450 400,450 1200,450 400,450 350,450 400,450 400,450 350,450 400,450 400,450 350,500 350,450 400,450 400,450 350,450 400,450 350,500 350,450 400,450 350,450 400,450 400,450 350,450 1250,400 400,450 350,500 400,400 450,400 400,450 1200,450 400,450 350,450 1250,450 350,450 400,450 1200,450 400,450 400,450 350,450 400,450 400,450 400,450

**Comment by z3t0** [comment]
Closed for inactivity, it seems #51 solves it.

**Comment by z3t0** [comment]
#51 remains unmerged.

**Comment by AnalysIR** [comment]
`RAWBUF` can be a max of 255. (based on `rawlen` see below)

This is because `rawlen` is defined as an unsigned 8 bit byte and controls filling up of the buffer when receiving signals. Defining `RAWBUF` as longer than 255 would just waste SRAM.

As an alternative, you could try using IRLib which allows for longer signals.

I don't believe this is a bug/issue, as the library is functioning as designed & probably OK to close off this issue.(?)

FYI: Quite a few signals are longer than 255 marks/space, in particular Air Conditioners.

**Comment by z3t0** [comment]
> As an alternative, you could try using IRLib which allows for longer signals

I'll look into that to see if we can improve this library by referring to it.

> I don't believe this is a bug/issue, as the library is functioning as designed & probably OK to close off this issue.(?)

Maybe I'll create a label for Feature Requests like this.
>FYI: Quite a few signals are longer than 255 marks/space, in particular Air Conditioners.

Which is why I dont really want to neglect this

**Comment by kennethtang4** [comment]
What you need to do is:

1. Increase RAWBUF to your desired value
2. Change the type of `rawlen` to uint16_t instead (which effectively lift the limit of the buffer to 65535)

Tested and worked (Came across here when I was looking around for solution).

**Comment by ArminJo** [comment]
Is implemented in the current version.
