### ISSUE TITLE
Feature request IrsendHardwired(?) 

### ISSUE THREAD

**Issue by gibbedy** [z3t0/Arduino-IRremote#494]
I would like to remove an IR receiver from a device and replace it with an arduino.

Is it trivial for someone to add another function for sending but without carrier frequency.

Thanks.

**Comment by AnalysIR** [comment]
You would also need to demodulate & invert the signal (like IR receivers do).

It is a function not included in the library (& in my opinion not likely)


Essentially all, you need to do is generate an inverted square wave to match.

HOWEVER, do not connect to mains powered devices unless you really know what you are doing, as there is a real risk of loss-of-life.

I suspect in  95%+ of cases using an IR emitter and receiver is better and provides isolation.

**Comment by bengtmartensson** [comment]
There are really two use cases here: 

1. generating true non-modulated protocols, (for example using the Revox, Barco, Archer protocols, or controlling RF senders, for example with a 433MHz sender with the arctech protocol),
2.  or just "skipping" the modulation, sending the same signal but without modulation.

For the first use case,  the present library does not support that directly, presently. (I support it directly in my library [Infrared4Arduino](https://github.com/bengtmartensson/Infrared4Arduino) though). You can rather easily (I would not say "trivial" though) to modify the current library to do the same thing. To support it "cleanly" in the current library is on the TODO list for future reorganization, IIRC. 

The second one (which is the only one AnalysIR treats), it is probably not a very good idea. You should try to bypass the decoding too. 

It just struck me that there are/were devices (Philips/Maranz, ("S-Bus"?), Sony S) ) that (I think) takes demodulated "electric" IR signals as input, so it may make sense there.

**Comment by gibbedy** [comment]
AnalysIR: Maybe I wasn't clear. I mean to remove the IR receiver from a $7 RGB lamp, and replace it with an arduino which will control the function of the lamp. If that was clear ignore this.

Regarding the risk. Are you talking about the general risk of playing inside 240VAC devices, or do I need to be concerned about chinese isolation between the 240VAC and the low voltage IR sensor input?
If it't the first I'll take my chances as in this case its all sealed up in solid epoxy or whatever that stuff is.

If it's the second then I don't want to be livening up my rs485 wiring.

Beng: I think i understand you and it's case 2 I'm doing. Unfortunately the decoding is buried in black resin.

**Comment by AnalysIR** [comment]
> Regarding the risk. Are you talking about the general risk of playing inside 240VAC devices, or do I need to be concerned about chinese isolation between the 240VAC and the low voltage IR sensor input?

I would say both & its nothing to do with Chinese as they also make some of the best tech available. The same applies to all mains devices.

> If it't the first I'll take my chances as in this case its all sealed up in solid epoxy or whatever that stuff is.

Except where you tap into it.

> If it's the second then I don't want to be livening up my rs485 wiring.

The bottom line is if you dont know the answer, you should avoid & remember that other people may 'touch' it when you are not around!!

What happens when a component in the epoxy fails short!

**Alternatives**
- Depending on the size of the unit...you can still use the Arduino to send the IR signal from close up, thus providing some isolation.....leaving only the power supply as an issue. 

- You mentioned rs485 wiring....why not just put the IR led on the end of a long wire instead!

**Comment by gibbedy** [comment]
Thanks for the reply and it's appreciated.
I edited my post multiple times and the word chinese was replaced with "dodgy cheap gear" which is what i specialize in  on ebay.

I'll leave  the 240VAC stuff alone.

The alternatives:
rs485 is just convenience and the reason alternatives don't interest me for this application, but I welcome suggestions. I've got a christmas lights setup with audio beat detection being passed over rs485 to remote arduino's in  backyard (thats the plan anyway).  I'm thinking I can just add this cheap lamp (actually its a 10W RGB floodlight) to the end of my rs485 run and add a byte in the message to control it.

I still think I would have a use for the function i ask for as there seems to be allot of cheap rgb stuff on ebay that use the same IR remote (apa 1616) that I wouldn't mind controlling with arduino without wiring Ir transmitter.

So just to confirm that irsend by hardwired connection is not an easy thing to code?
Thanks again.

**Comment by AnalysIR** [comment]
Glad it all worked out :)

**Comment by GeorgeIoak** [comment]
I'm looking to do the same/similar thing. I'd like to bypass the IR modulation and remove the IR LED and IR Receiver and connect directly to the processor pin on the receiving unit. @gibbedy did you achieve this and if so how?

@bengtmartensson Is this what your IRSenderNonMod from your Infrared4Arduino does?

**Comment by bengtmartensson** [comment]
> Is this what your IRSenderNonMod from your Infrared4Arduino does?

Strictly speaking, it solves use case 1 (from my first post), but practically speaking, anything that solves use case  1 solves use case 2 too. Be sure you find out if a level inversion is needed or not.

It may be a good idea to use an opto-coupler between the Arduino and the to-be-controlled device.

**Comment by GeorgeIoak** [comment]
Yes, level inversion is needed and I do plan on using an opto-coupler. With my testing I am using 
`irsend.sendNEC(0x807FD02F, 32);`
In your [example](https://github.com/bengtmartensson/Infrared4Arduino/blob/master/examples/IrSignalNonMod/IrSignalNonMod.ino) it uses the time spacing, do I have to convert my string to this?

**Comment by bengtmartensson** [comment]
> Yes, level inversion is needed and I do plan on using an opto-coupler. 

Kewl. Note that the opto-coupler does the inversion, if you use it the "normal" way.

> In your example it uses the time spacing, do I have to convert my string to this?

The term we use is "raw signal". Infrared4Arduino uses a [completely different API](http://www.harctoolbox.org/infrared-apidocs/index.html) from that of IRremote. (For example, it is `irSignal = Nec1Renderer::newIrSignal(0x80, 0x7F, 0xD0)` instead of `sendNec(0x807FD02F, 32)`.)  But it can be done.  Something like (untested)

```
IrSenderNonMod sender(NON_MOD_PIN);
...
irSignal = Nec1Renderer::newIrSignal(0x80, 0x7F, 0xD0);
...
sender.sendIrSignal(irSignal);
```
