### ISSUE TITLE
AtTiny85 sendRaw doesn't work correctly

### ISSUE THREAD

**Issue by iskander-g** [z3t0/Arduino-IRremote#495]
**Board:** Attiny85
**Library Version:** last
**Protocol:** raw

**Code Block:**
https://gist.github.com/iskander-g/49b794212eb578911918cc764b98f5f0

I'm trying to send a raw signal in 11 bits, simple int encoded in this bits.

This code works fine on arduino uno and arduino mini pro, but doesnt work on attiny85.

I have IR led on pin1 (hardware pin6) connected directly to pin1 and ground.
Also i have Led connected to pin 0 and ground.

I'm using custom recevier for my transponders, and it shows me:
```
got data: 7 bits
1:450 ZERO
2:500:  ONE
3:350 ZERO
4:350 ZERO
5:300 ZERO
6:1550:  ONE
7:250 ZERO
value: 544.0000000000
got data: 7 bits
1:350 ZERO
2:450 ZERO
3:350 ZERO
4:2250:  ONE
5:250 ZERO
6:500:  ONE
7:300 ZERO
value: 160.0000000000
got data: 5 bits
1:300 ZERO
2:600:  ONE
3:350 ZERO
4:1400:  ONE
5:200 ZERO
```

Sometimes it receives 5 bits, sometimes 7 bits, but never 11 and never value 300 from attiny 85. 
But it correctly works on Mega 2560 and arduino uno and arduino pro mini and receives 300.

this is result that i usually see from mega2560 or uno:

```
got data: 9 bits
1:200 ZERO
2:300 ZERO
3:500: ONE
4:250 ZERO
5:250 ZERO
6:500: ONE
7:250 ZERO
8:600: ONE
9:550: ONE
value: 300.0000000000
got data: 11 bits
1:250 ZERO
2:250 ZERO
3:500: ONE
4:300 ZERO
5:200 ZERO
6:550: ONE
7:250: ZERO
8:550: ONE
9:550:  ONE
10:250 ZERO
11:250 ZERO
value: 300.0000000000
```

i never saw signals with length 2250 or 1400 from UNO or mega, but i always receive it from Attiny 85.

How i can fix it? 

Edit: fixed formatting by z3t0

**Comment by AnalysIR** [comment]
I suggest you start trying to get the basic examples working on the '85 first. (with a simple TV signal)

...to eliminate any potential confilcts with the other library being used.
