### ISSUE TITLE
Arduino Due Support

### ISSUE THREAD

**Issue by mataide** [z3t0/Arduino-IRremote#504]
There is any plan to support Arduino Due?
Or any start point that I can look into?

Thanks

**Comment by bengtmartensson** [comment]
I have a Due (cheap clone) since two years, but it has not yet seen electricity...

If you want to start working, check out the "beta" branch, or  https://github.com/z3t0/Arduino-IRremote/releases/tag/v2.4.0.

**Comment by mataide** [comment]
Ok, I will check out.

**Comment by ArminJo** [comment]
Sam and SAMD support is now included.

**Comment by bengtmartensson** [comment]
In case someone is interested, Due is supported in [Infrared4Arduino](https://github.com/bengtmartensson/Infrared4Arduino).

The Due is actually, despite of its age and (lack of) popularity, quite a cool board...
