### ISSUE TITLE
Removing ASCII "art"?

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#506]
I am not really a fan of art in plain text, especially not in source code. I would like to remove the large headings in files (see screenshot) if no one is opposed.

![img](https://i.imgur.com/fgUbNiW.png)

Suggested alternative....

![img](https://i.imgur.com/xm8ubjl.png)

**Comment by jassing** [comment]
Change it. I am old, but for standout notations, I like
/***********
  ** Sony **
***********/
But the asci art should go.

**Comment by z3t0** [comment]
That's good enough for me, glad to know I'm not the only one bothered by it :smile:

**Comment by bengtmartensson** [comment]
Ascii art banners is definitely not a technology for 2017. 

Instead, I suggest file comments of Doxygen, see #461.

Aside: in some situations, "ascii art" (not banners) can be useful, see [these nice examples](http://busyducks.com/wp_4_1/2015/11/16/ascii-art-arduino-pinouts/).

**Comment by ArminJo** [comment]
It looks a bit retro, so why not keep it.
