### ISSUE TITLE
beta branch: add (sensible) paragraph to library.properties

### ISSUE THREAD

**Issue by bengtmartensson** [z3t0/Arduino-IRremote#510]
Continuation of #464, #507.

The [Arduino library specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) is unclear upon if `paragraph` is required in `library.properties`. It was recently removed in the beta branch. With Arduino IDE 1.8.3 and Linux (Fedora 26), this leads to the warning messages (for example when opening the library manager)
```
Invalid library found in /home/bengt/Arduino/libraries/IRremote: Missing 'paragraph' from library
Invalid library found in /home/bengt/Arduino/libraries/IRremote: Missing 'paragraph' from library
Invalid library found in /home/bengt/Arduino/libraries/IRremote: Missing 'paragraph' from library
Invalid library found in /home/bengt/Arduino/libraries/IRremote: Missing 'paragraph' from library
Invalid library found in /home/bengt/Arduino/libraries/IRremote: Missing 'paragraph' from library
Invalid library found in /home/bengt/Arduino/libraries/IRremote: Missing 'paragraph' from library
Invalid library found in /home/bengt/Arduino/libraries/IRremote: Missing 'paragraph' from library
Invalid library found in /home/bengt/Arduino/libraries/IRremote: Missing 'paragraph' from library
```

So I suggest that is filled with a sensible content. Note that is should only make sense when preceded by the sentence of `sentence`.

**Comment by z3t0** [comment]
I also found this message as an error (sometimes) when uploading/compiling.

**Comment by hballinas** [comment]
How do I unsubscribe to this email chain?

**Comment by z3t0** [comment]
There is an unsubscribe button on the right side of this issue (on GitHub). Or you can unwatch at the top of the repository.
