### ISSUE TITLE
BANG OLUFSEN protocol

### ISSUE THREAD

**Issue by Galysh** [z3t0/Arduino-IRremote#511]
I implement the protocol in the library. I have experience. Faced the problem of getting a repeat command. I do not receive a RAW signal from the library, since there is no pause between parcels. How can I fix the problem?
Where can I send my handbags?

Encoding  : BANG_OLUFSEN
Code      : A0D9 (20 bits)
Timing[43]: 
     + 200, -2900     + 200, -2900     + 200, -15300     + 200, -2900
     + 200, -9050     + 200, -2900     + 200, -9100     + 200, -2900
     + 200, -6000     + 200, -6000     + 200, -6000     + 200, -6000
     + 200, -9050     + 200, -6000     + 200, -2900     + 200, -9100
     + 200, -6000     + 200, -2900     + 200, -6000     + 200, -9050
     + 200, -12200     + 200
unsigned int  rawData[43] = {200,2900, 200,2900, 200,15300, 200,2900, 200,9050, 200,2900, 200,9100, 200,2900, 200,6000, 200,6000, 200,6000, 200,6000, 200,9050, 200,6000, 200,2900, 200,9100, 200,6000, 200,2900, 200,6000, 200,9050, 200,12200, 200};  // BANG_OLUFSEN A0D9
unsigned int  data = 0xA0D9;

**Comment by Galysh** [comment]
P.S.
https://github.com/z3t0/Arduino-IRremote/issues/56

To sum up the information I got so far the protocol is as follows:
Frequency: 455 kHz
Coding: pulse distance
Frame: 4 start bits + 16 data bits + 1 trailer bit + 1 stopbit
Data: 0 address-bits + 16 command bits
Start-Bit 1: 200µs puls, 2925µs pause
Start-Bit 2: 200µs puls, 2925µs pause
Start-Bit 3: 200µs puls, 15425µs pause
Start-Bit 4: 200µs puls, 2925µs pause
0-Bit: 200µs puls, 2925µs pause
1-Bit: 200µs puls, 9175µs pause
R-Bit: 200µs puls, 6050µs pause, repetition of last bit
Trailer bit: 200µs puls, 12300µs pause
Stop bit: 200µs puls
Repetition: none
Pushbutton repetition: N-times repetition of original-frames within 100ms
Bit order: MSB first
(Source: http://www.mikrocontroller.net/articles/IRMP#B.26O)

**Comment by bengtmartensson** [comment]
Two questions:

1. How did you get those captures? TSOP7000?
2. Has anyone tried to send 455kHz modulated IR? My gut feeling is that a 16MHz CPU will not do it, but I prefer facts.

> I do not receive a RAW signal from the library,

what receiver are you using?

**Comment by AnalysIR** [comment]
> Has anyone tried to send 455kHz modulated IR? My gut feeling is that a 16MHz CPU will not do it, but I prefer facts.

Yes, It works fine with 16MHz AVRS/Arduinos and most other MCUs. The carrier(PWM) ends up within circa 10kHz (High or Low),...from memory, which is fine. If you need specifics, it can be worked out with clock/timer calculators for the specific platform/clock/timer. Obviously, 455,000.00Hz is not available exactly due to clock dividers etc. A custom crystal is required to get 455kHz exactly. (+/- xxPPM of the crystal)

Responsivity is well within 95% @+/- 10% of the nominal carrier frequency. So +/- 10kHz is essentially spot on/more than good enough.

_PS: tested with 'genuine' TSOP7000s (some fakes around & AFAIK genuine ones are EOL, no longer in production)_

**Comment by Galysh** [comment]
Is my code interesting? Can I expect to add it to the library?

Can anyone help me in getting the hold code from the timer?

**Comment by z3t0** [comment]
Your code will definitely be added to the library if you submit a PR. Though it may take a while since all contributors to this project work on their own free time as volunteers :smile:

Your contribution is greatly appreciated!
