### ISSUE TITLE
query

### ISSUE THREAD

**Issue by dunk8888** [z3t0/Arduino-IRremote#524]
Hi can you help me understand why the bellow code differs from the same key press.
Ime trying understand a sketch some one wrote,the key codes bellow are from the same buttons on the same remote,but the two sketches differ like bellow,i just cant understand whats going on.
I CANT UNDERSTAND WHY THEY ARE DIFFERANT.

#define IRKEY_ONE    0x010  
#define IRKEY_TWO    0x810
#define IRKEY_THREE  0x410
#define IRKEY_FOUR   0xc10

Same remote and buttons as above,
but the code differs??
#define IRKEY_ONE    0x80  
#define IRKEY_TWO    0x81  
#define IRKEY_THREE  0x82  
#define IRKEY_FOUR   0x83

**Comment by AnalysIR** [comment]
the bit order is just reversed :)

convert to binary and you will see the pattern

**Comment by z3t0** [comment]
I think this has been solved :smile:

**Comment by dunk8888** [comment]
Oh right,so i need a hex to binary converter? ile have a look and see if i can figure it out lol ime new to binary hex etc will keep me busy.thanks

**Comment by dunk8888** [comment]
Why has this been done?

**Comment by dunk8888** [comment]
Thanks i can see now,i can add my own remote codes to an existing project,brill thanks again.

**Comment by dunk8888** [comment]
Is it somthing to do the way its read from memory? One sketch uses pgmspace
and the other doesnt so ime thinking its going into memory or somthing then
getting switched round or read backwards msb lsb etc so the code has to be
switched to start with,am i on the wright track or no? lol ime just trying
to figure it out why has it been done that way?
