### ISSUE TITLE
send of NEC 64bits

### ISSUE THREAD

**Issue by AsTiger117** [z3t0/Arduino-IRremote#526]
Hi friends.
I have a trouble with send of 64 bits. Is there any solution?
irsend.sendNEC(0x6057000000D1020D,64);

thanks for your help.

**Comment by bengtmartensson** [comment]
Short answer: no, there is no easy and natural solution.

The first argument sendNEC is an unsigned long, which is 32 bits on "most" (all?) boards.  I suspect the compiler issues a warning when you try to assign 0x6057000000D1020D to that parameter.

**Comment by AsTiger117** [comment]
Yes. This is the message: warning: large integer implicitly truncated to unsigned type [-Woverflow]

**Comment by kyet** [comment]
@AsTiger117 
sendNEC(..) consists of 
- sendNEC_header()
- sendNEC_data(..)
- sendNEC_footer()
These member functions are private.
If you change this to public, we could write like this,
```
irsend.sendNEC_header();
irsend.sendNEC_data(0x60570000, 32);
irsend.sendNEC_data(0x00D1020D, 32);
irsend.sendNEC_footer();
```

**Comment by AnalysIR** [comment]
or just write your own custom funtion using iresend.mark & irsend.space
...as we show on our blog [](https://www.analysir.com/blog/2015/09/01/simple-infrared-pwm-on-arduino-part-3-hex-ir-signals/)

_{The example shows the use of softPWM,which can be easily swapped with the built-in IRremote mark & space functions)_

**Comment by ArminJo** [comment]
You can copy the function sendNEC and use the function sendPulseDistanceWidthData(NEC_BIT_MARK, NEC_ONE_SPACE, NEC_BIT_MARK, NEC_ZERO_SPACE, data, nbits); multiple times.
