### ISSUE TITLE
Automatic generation of code for protocols

### ISSUE THREAD

**Issue by bengtmartensson** [z3t0/Arduino-IRremote#536]
My project [IrpTransmogrifier](https://github.com/bengtmartensson/IrpTransmogrifier) can now generate IRremote code for most of the IR protocols it knows. Presently only sending (not decoding) is implemented. There is a reasonably detailed description [contained therein](https://github.com/bengtmartensson/IrpTransmogrifier/blob/master/src/main/doc/IRremote-protocols.md).

To use, the [development version](https://github.com/bengtmartensson/IrpTransmogrifier/releases/tag/ci-build) needs to be installed.

There are a some problems and "quirks". (For example: The protocol parametrization is in general completely different. "My" protocols end with a space of protocol specific length > 0.)  Most of these (IMHO) comes from design flaws in IRremote. I have tried here not to fix these problems. 

I do not want to scare anyone away, but some software development experience outside of Arduino is highly desirable...

How can this be "integrated"? Should it at all? Possibly generate a few protocols "on demand"? Feedback and suggestions of all sort are welcome! (Right now, I do not want to write a PR.)

**Comment by z3t0** [comment]
I think this is a really interesting idea and should be integrated into this project, at least on some level.

**Comment by bengtmartensson** [comment]
Closing this, since it does not make sense without more work. Maybe I will take up the idea later.

It someone cares, [this project](https://github.com/bengtmartensson/IrProtocolCodeGeneration) contains some unfinished code.
