### ISSUE TITLE
Change output pin Arduino Pro Mini

### ISSUE THREAD

**Issue by Luc3as** [z3t0/Arduino-IRremote#537]
**Board:** ARDUINO Pro Mini
**Library Version:** 2.1.0

Hi, I am trying to figure out if it is possible to change output pin at Atmega328p, from pin 3 to other, in my case 6. both should be able of PWM, I tried to change this declaration in library boarddefs.h but I cannot get it working. 
Reason for this is as I am using both pins 2 and 3 for interrupts, by PIR sensors.

thanks

**Comment by AnalysIR** [comment]
you can change to **pin 9**, by modifying the file
boarddefs.h
```
#else
// Arduino Duemilanove, Diecimila, LilyPad, Mini, Fio, Nano, etc
// ATmega48, ATmega88, ATmega168, ATmega328
	//#define IR_USE_TIMER1   // tx = pin 9    <======  Uncomment
#define IR_USE_TIMER2 // tx = pin 3<======  Comment
```
