### ISSUE TITLE
I want KENWOOD AC remote code

### ISSUE THREAD

**Issue by Najab** [z3t0/Arduino-IRremote#538]
If any one have KENWOOD AC remote code for ON/OFF and Change TEMPERATURES in the form of RAW Data please provide for me.
Thanks in advance.

**Comment by AnalysIR** [comment]
I am not sure you will get that info readily, with the information provided.

It might help to specify which model# of AC unit (not just the make) and also the model# of remote control.

FYI: You can get AC remotes online from China, for a few $ delivered. Then you could use an Arduino to capture the RAW signals. (Also available via Amazon for a couple $ more)

**Comment by Najab** [comment]
I already have AC remote but i can't read accurate RAW signals for KENWOOD AC.

**Comment by AnalysIR** [comment]
OK...in that case a search of the issues here would have provided a solution....

Try using the following sketch, to record the RAW timings:
[Air Conditioners: Recording long Infrared Remote control signals with Arduino](https://www.analysir.com/blog/2014/03/19/air-conditioners-problems-recording-long-infrared-remote-control-signals-arduino/)

**Comment by Najab** [comment]
I already try this
