### ISSUE TITLE
How to capture a several button presses in an array and stop when a certain button is pressed

### ISSUE THREAD

**Issue by denden4444** [z3t0/Arduino-IRremote#545]
Hi 
I'm hoping some kind soul can help me.
With reference to this link : [https://github.com/z3t0/Arduino-IRremote/wiki/Receiving-with-the-IRremote-library](url)
I would like to capture each code that's received (each key in other words) from the remote into an array until a certain key is pressed.

For example the array would hold something like : 
0x2FD01FE0
0x2FD01FD0
0x2FD01FB0 
etc

I just need a simple example of this because I'm really battling with creating the correct array type and printing it out etc.

Thank you 

Den
**Board:** ARDUINO UNO
**Library Version:** 2.1.0
**Protocol:** Sony (if any)

**Code Block:**
```c

#include <IRremote.h> 

.....

```

Use [a gist](gist.github.com) if the code exceeds 30 lines

**checklist:**
- [] I have **read** the README.md file thoroughly
- [] I have searched existing issues to see if there is anything I have missed.
- [] The latest [release](https://github.com/z3t0/Arduino-IRremote/releases/latest) is used
- [] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here
- [] The title of the issue is helpful and relevant 

** We will start to close issues that do not follow these guidelines as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

The above is a short template allowing you to make detailed issues!

**Comment by ArminJo** [comment]
I dare you must code it by yourself.
