### ISSUE TITLE
ESP32 crash using this library

### ISSUE THREAD

**Issue by Vorms** [z3t0/Arduino-IRremote#559]
Hello,
I test the library with a small project and it work as expected.
I include the library in a larger project and the esp crash.
here is the dump of the crash:

0x40084abd: xQueueGenericReceive at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/./queue.c line 1995
0x400875f4: invoke_abort at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/./panic.c line 578
0x400876f3: abort at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/./panic.c line 578
0x40084abd: xQueueGenericReceive at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/./queue.c line 1995
0x400d6343: ledcWrite at D:\Users\Thierry\Documents\Arduino\hardware\espressif\esp32\cores\esp32/esp32-hal-ledc.c line 164
0x400d5301: IRsend::mark(unsigned int) at D:\Users\Thierry\Documents\Arduino\libraries\ESP32-IRremote/irSend.cpp line 40
0x400d5481: IRsend::sendSony(unsigned long, int) at D:\Users\Thierry\Documents\Arduino\libraries\ESP32-IRremote/ir_Sony.cpp line 28
0x400d4f1d: MilesTag::sendIrCode(unsigned long) at D:\Users\Thierry\Documents\Arduino\libraries\MilesTag/MilesTag.cpp line 77
0x400d3e59: BoxLib::cycleIrMessage(unsigned int, unsigned char, unsigned char, unsigned char, char*, bool) at D:\Users\Thierry\Documents\Arduino\libraries\BoxLib/BoxLib.cpp line 936
0x400d183e: IdBox::checkReceiveDone(bool) at D:\Users\Thierry\Documents\Arduino\libraries\IdBox/IdBox.cpp line 259
0x400d1127: loop() at D:\Users\Thierry\Documents\Arduino\idBox/idBox.ino line 53
0x400ece05: loopTask(void*) at D:\Users\Thierry\Documents\Arduino\hardware\espressif\esp32\cores\esp32/main.cpp line 18 (discriminator 1)

Please help me to solve this issue.
Best regards

Thierry Vorms vormsty@gmail.com

**Comment by ArminJo** [comment]
Please check again with the new library version from this repository.
