### ISSUE TITLE
toggle bit warning in RC6 and RC5 send functions - ir_RC5_RC6.cpp

### ISSUE THREAD

**Issue by rifotu** [z3t0/Arduino-IRremote#565]
Hello,

Shouldn't we add the below warning in IRsend:sendRC5 function too?

// NB : Caller needs to take care of flipping the toggle bit

Currently it's only in the void IRsend::sendRC6 (unsigned long data, int nbits) function comments

Thank you

**Comment by ArminJo** [comment]
Thanks but now obsolete since of new function sendRC5ext(uint8_t addr, uint8_t cmd, boolean toggle)
