### ISSUE TITLE
IR sender problem

### ISSUE THREAD

**Issue by artwebstudios** [z3t0/Arduino-IRremote#569]
Hi there!

I'm new with the IRremote library for Arduino.  I've been not able to send successful signals to any devices. I have review all documentation and made some test without any result. 

I have the hardware setup as the documentation. I tried the example IRrecvDumpV2 for reading power on/off signals for a couple of devices SmartTV and Haier AC and I got both HEX and DEC codes. It works perfect! However, when I tried to send IR signals to any device I had no response. 

This is the code I used for LG SmartTV

**Code Block:**
```c

#include <IRremote.h>

IRsend irsend;

void setup()
{
}

void loop() {
		irsend.sendNEC(0x20DF10EF,32); //SEND IR PULSES LG TV POWER
		delay(5000);
	}
.....
*Note: I have tried as well a for bucle of 3 times with 40ms delay with no results. 

This is the code I used for Haier AC

**Code Block:**
```c

#include <IRremote.h>

IRsend irsend;

void setup()
{

}

void loop() {
  int khz = 38; // 38kHz carrier frequency for the NEC protocol
  unsigned int irSignal[] = {3150,2950, 3100,4300, 650,1550, 600,450, 650,1600, 600,450, 650,450, 650,1550, 600,1600, 600,450, 650,450, 650,450, 600,1550, 650,1600, 600,450, 650,450, 650,1550, 600,450, 650,450, 650,450, 650,450, 600,450, 650,450, 650,450, 650,450, 650,400, 650,450, 650,450, 650,450, 650,400, 650,450, 650,450, 650,450, 650,450, 600,450, 650,1600, 600,450, 650,450, 600,450, 650,450, 650,450, 650,450, 650,400, 650,450, 650,1550, 650,450, 650,450, 600,450, 650,450, 650,450 };  // UNKNOWN 23AD77AF

  irsend.sendRaw(irSignal, sizeof(irSignal) / sizeof(irSignal[0]), khz); //Note the approach used to automatically calculate the size of the array.

  delay(5000); //In this example, the signal will be repeated every 5 seconds, approximately.
}

.....

Basically, I upload the codes and move the Arduino with the IR LED on the breadboard with a 9V battery. I point the IR LED to the TV or AC  IR receiver but I have no response. The IR LED is from the MTARDREMITE kit from KEYES. It seems is working well because it illuminate when sending signal. Even is quite simple, I checked several time the hardware setup. There is attached a photo. 
![img_1311](https://user-images.githubusercontent.com/16102684/39697431-34a1ee54-51f1-11e8-8f29-d029a52a1851.jpg)

I hope I can get some ideas why is not working. I'm sorry in advance if there is a big silly mistake behind this problem. 

Thanks,
Andrés

```
**Board:** ARDUINO UNO
**Library Version:** 2.1.0
**Protocol:** NEC AND UKNOWN
![img_1311](https://user-images.githubusercontent.com/16102684/39697450-4409fa08-51f1-11e8-9913-64b6260015e1.jpg)

**Comment by AnalysIR** [comment]
First thing to check is if you have the IR LED connected the right way around. _(search online if you don't know how)_

Then look at the IR LED when sending thru the camera on a phone and see if you can see it blinking/flashing when a signal is sent

Also, make sure to bring the LED close to the target device and point the top of the LED towards the device.

Finally, stick with the NEC signal first and only move onto the AC once you have that working. (Much simpler)

_PS: Its great to see posters sticking to the guidelines on posting & posting useful/relevant information, showing what has been tried using code tags etc...tnx++  :) _

**Comment by artwebstudios** [comment]
Hi AnalysIR, 

Thanks for your quick reply. 

I've doble check the hardware setup and It seems fine. It is connected as the attached sketch. 

I can see the IR LED flashing when signal is sent without any camera. Do IR LEDs emit visible light? Mine does emit a violet light.  I bought this kit  http://www.yd-tech.com.tw/product_info.php/products_id/71970 in a trip to Taiwan. There is any info in english so I supposed the LED it is a IR LED but stating to have some doubts.  Ill try to get another IR LED to check. 

PS: New here .. I tried to keep to the rules! I hope this behaviour continues in the future :-)

**Comment by AnalysIR** [comment]
Aaaaah!
I believe you have an IR LED of the wrong wavelength. 944nm is the correct wavelength (You likely have 850nm)

What a difference a few nm make :)

The 850nm are typically used in night time cameras/CCTV & can how a dim visible light as you described.

So yes a good 944nm one is what you want. TSAL6100/TSAL6400/TSAL6400 sre good quality choices from Vishay.
An old unused remote control is a quick way to get one...even as a temporary workaround.

**Comment by artwebstudios** [comment]
You are right!
I just took the IR LED from an old remote and works perfectly!  
Now I have to make it work together with Aurdino Firmata lib and Processing. 
Thanks for your help!
