### ISSUE TITLE
IRsend not working 100% of the time

### ISSUE THREAD

**Issue by JBrowne031** [z3t0/Arduino-IRremote#570]
I have made a program using an Arduino Uno to receive IR signals from a remote that uses NEC. If I press the "1" button on my remote, the program uses an IF statement to print the button value "1" on an LCD. Once the value is displayed, the program sends the NEC value to a IR transmitter/emitter using irsend.sendNEC(0xXXXXXXX, 32) followed by a delay and the irrecv enableIRin(). My question is, how does a signal randomly get missed when it is sent to the device after it has been displayed? Is the IR emitter too close or too far away? Does the delay value have to be something larger than 1 seconds? Do I need a stronger IR emitting sensor?

I am using the IRremote library along with the liquidcrystal library. Not really any issues other than signalling not being received by the device consistently.

I expect the device to receive the same amount of signals every time, but it randomly misses signals that are being sent. This causes the LCD to read "1.23 24 10000" and the sign to read "1.2 241000". In this example the "3", " ", and "0" were received and printed to the LCD, but the sign missed the signals and caused a different printout. The whole project I am doing is entering and displaying in 1 room and sending it into another room (which uses a led sign).

My code is relatively simple. It has some cases of redundancy (can fix, but shouldnt be cause of IR not working all the time). Im open to any suggestions as to why this doesnt send properly 100% of the time.

Please review my code and let me know what you think. It works but not 100% of the time.

#include <IRremote.h>
#include <LiquidCrystal.h>

int receiverpin = 2;
IRrecv irrecv(receiverpin);
decode_results results;
IRsend irsend;
LiquidCrystal lcd(12, 11, 5, 4, 8, 7);
int value;
int cursorRow = 0;
int cursorCol = 0;

void setup() {
  
  lcd.begin(16, 2);
  pinMode(receiverpin, INPUT);
  Serial.begin(9600);
  irrecv.enableIRIn();
  lcd.cursor();
  lcd.blink();
  lcd.clear();
  
}

void loop() {

  if(irrecv.decode(&results)){
    Serial.println(results.value, HEX);
    delay(1000);
    irrecv.enableIRIn();
    
    if (results.value == 0x3FCE817) //program button
    {
      Serial.println("program");
      lcd.setCursor(0,1); //lcd displays P on the bottom left hand corner and disappears after 1 second..
      lcd.print("P");
      delay(1000);
      lcd.clear();
      delay(1000);
      irsend.sendNEC(0x3FCE817, 32);  //3 program button sends to test IR emitter functionality..
      delay(455);
      irsend.sendNEC(0x3FCE817, 32);  //usually has 2 beaps and misses 1 send command..
      delay(455);
      irsend.sendNEC(0x3FCE817, 32);  //tried 5000 delay with serial print and had same issue..  
      delay(455);
      irrecv.enableIRIn();
      irrecv.resume();
    }
    if (results.value == 0x3FC48B7) //run button
    {
      for (int positionCounter = 0; positionCounter < 20; positionCounter++) 
      {
        // scroll position left:
        lcd.scrollDisplayRight();
        delay(150);
      }
      for (int positionCounter = 0; positionCounter < 36; positionCounter++) 
      {
        // scroll position right:
        lcd.scrollDisplayLeft();
        delay(150);
      }
      for (int positionCounter = 0; positionCounter < 16; positionCounter++)
      {
        // scroll position left:
        lcd.scrollDisplayRight();
        delay(150);
      }
      //above is a visual representation of the signal sending to the sign..
      delay(500);
      lcd.clear(); //signal sending so the entered fields can be removed..
      irsend.sendNEC(0x3FC48B7, 32);
      delay(455);
      irsend.sendNEC(0x3FC48B7, 32);  //send 2 times for sign to run entered program
      delay(455);
      irrecv.enableIRIn();
      irrecv.resume();  //not sure if these are needed..
    }
    if (results.value == 0x3FC807F) //1 button
      {
        lcd.print("1");
        delay(1000);
        irsend.sendNEC(0x3FC807F, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();   
        cursorCol++;
      }
      if (results.value == 0x3FC40BF) //2 button
      {
        lcd.print("2");
        delay(1000);
        irsend.sendNEC(0x3FC40BF, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();   
        cursorCol++;
      }
      if (results.value == 0x3FCC03F) //3 button
      {
        lcd.print("3");
        delay(1000);
        irsend.sendNEC(0x3FCC03F, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();   
        cursorCol++;
      }
      if (results.value == 0x3FC6A95) //delete button
      {
        cursorCol = cursorCol-1;
        lcd.setCursor(cursorCol, cursorRow);  //set lcd display back one space and clear it..
        delay(200);
        lcd.print(" ");
        delay(1000);
        irsend.sendNEC(0x3FC6A95, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        lcd.setCursor(cursorCol, cursorRow);
      }
      if (results.value == 0x3FCE21D) //space button
      {
        lcd.print(" ");
        delay(1000);
        irsend.sendNEC(0x3FCE21D, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
      if (results.value == 0x3FCCA35) //! button used with select button to create "."
      {
        lcd.print("."); //send code will need to implement 0x3FCCA35 function along with 0x3FCDA25 functions
        delay(1000);
        irsend.sendNEC(0x3FCCA35, 32);  //! button
        
        Serial.print("!");
        delay(455);
        irsend.sendNEC(0x3FCDA25, 32);  //select button
        
        Serial.print("Select 1");
        delay(455);
        irsend.sendNEC(0x3FCDA25, 32);  //select button
        
        Serial.print("Select 2");
        delay(455);
        irsend.sendNEC(0x3FCDA25, 32);  //select button
        
        Serial.print("Select 3");
        delay(455);
        irsend.sendNEC(0x3FCDA25, 32);  //select button
        
        Serial.print("Select 4");
        delay(455);
        irsend.sendNEC(0x3FCDA25, 32);  //select button
        
        Serial.print("Select 5");
        delay(455);
        irsend.sendNEC(0x3FCDA25, 32);  //select button
        
        Serial.print("Select 6");
        delay(455);
        irsend.sendNEC(0x3FCDA25, 32);  //select button
        
        Serial.print("Select 7");
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
      if (results.value == 0x3FC20DF)  //4 button
      {
        lcd.print("4");
        delay(1000);
        irsend.sendNEC(0x3FC20DF, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
      if (results.value == 0x3FC18E7) //5 button
      {
        lcd.print("5");
        delay(1000);
        irsend.sendNEC(0x3FC18E7, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
      if (results.value == 0x3FCA05F) //6 button
      {
        lcd.print("6");
        delay(1000);
        irsend.sendNEC(0x3FCA05F, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
      if (results.value == 0x3FC609F) //7 button
      {
        lcd.print("7");
        delay(1000);
        irsend.sendNEC(0x3FC609F, 32); 
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
      if (results.value == 0x3FCE01F) //8 button
      {
        lcd.print("8");
        delay(1000);
        irsend.sendNEC(0x3FCE01F, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
      if (results.value == 0x3FC10EF) //9 button
      {
        lcd.print("9");
        delay(1000);
        irsend.sendNEC(0x3FC10EF, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
      if (results.value == 0x3FC38C7) //0 button
      {
        lcd.print("0");
        delay(1000);
        irsend.sendNEC(0x3FC38C7, 32);
        delay(455);
        irrecv.enableIRIn();
        irrecv.resume();
        cursorCol++;
      }
    }
  }

**Comment by AnalysIR** [comment]
Some comments:

you would be better off use case statements instead of the if statements (If you stick with IF try making use of ELSE IF

In some of the paths...there could be a delay of up to 5 secs....so it is possibe you could miss signals due to these delays.

also you shouldnt really need those delays after the lcd functions.

Try improving the code as above and post back.
(It is likely an issue with your code vs use of the remote)

PS: Not all of your code above is contained within code taga <>, please re-edit to clean it up.
