### ISSUE TITLE
Multiple Code Receiving

### ISSUE THREAD

**Issue by pradeep-techens** [z3t0/Arduino-IRremote#575]
Hi, When I am capturing the code from remote then I am receiving 4 code. for ac when I am using universal remote then i am receiving 2 code. I am using these 2 code /4 code from sender then ac not responding. Can you please let me know why remote sending multiple codes for a single command. Please let know why it is not working from my sender. Is there any specific way to send the codez?

here is the example of four code for on command

Encoding  : NEC
Code      : 946D160A (32 bits)
Timing[73]: 
first bit
180

unsigned int  rawData[73] = {9000,4450, 700,1650, 700,550, 700,550, 700,1650, 700,550, 700,1650, 700,550, 700,550, 700,550, 700,1650, 700,1650, 700,550, 700,1650, 700,1650, 700,550, 700,1650, 700,550, 700,550, 700,550, 700,1650, 700,550, 700,1650, 700,1650, 700,550, 700,550, 700,550, 700,550, 700,550, 700,1650, 700,550, 700,1650, 700,550, 700,550, 700,1650, 700,550, 700};  // NEC 946D160A
unsigned int  data = 0x946D160A;

Encoding  : UNKNOWN
Code      : FBBF75CC (32 bits)
Timing[65]: 
first bit
14

unsigned int  rawData[65] = {700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,1650, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,1650, 700,1650, 700,550, 700,550, 700};  // UNKNOWN FBBF75CC

Encoding  : NEC
Code      : 946D1606 (32 bits)
Timing[73]: 
first bit
180

unsigned int  rawData[73] = {9000,4450, 700,1650, 700,550, 700,550, 700,1650, 700,550, 700,1650, 700,550, 700,550, 700,550, 700,1650, 700,1650, 750,500, 700,1650, 700,1650, 700,550, 700,1650, 700,550, 700,550, 700,550, 700,1650, 700,550, 700,1650, 700,1650, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,1650, 700,1650, 700,550, 700,550, 700,1650, 700,550, 700};  // NEC 946D1606
unsigned int  data = 0x946D1606;

Encoding  : UNKNOWN
Code      : 9089C006 (32 bits)
Timing[65]: 
first bit
14

unsigned int  rawData[65] = {700,550, 700,1650, 700,550, 700,1650, 700,550, 700,550, 700,1650, 700,550, 700,550, 700,550, 700,1650, 700,1650, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,550, 700,1650, 700,550, 700,550, 700,1650, 700,550, 700,1650, 700,550, 700};  // UNKNOWN 9089C006

**Comment by AnalysIR** [comment]
Your first & third signals abve are normal NEC 32 bit signals.
 
Your second & fourth signals above are just partial signals. This could be caused by battery or the way you are using/pointing the remote.

So just make sure you hold the remote about 1m or 3ft away from the IR receiver when capturing. Also point it directly at the receiver.

You will know when you have a good capture when the first two values are close to 9000 / 4500 and teh lenght is [**73**] (or more)
