### ISSUE TITLE
Checksum Calculation !!!

### ISSUE THREAD

**Issue by Kinjalk** [z3t0/Arduino-IRremote#578]
Hello,
These are some  Encoded data for Hitachi AC
B2AE4D91F061A8000000002018 => 1011  0010  1010  1110  0100  1101  1001  0001  1111  0000  0110  0001  1010  1000  0000  0000  0000  0000  0000  0000  0000  0000  0010  0000  0001  1000  

B2AE4D91F028A80000000020F0=>
1011  0010  1010  1110  0100  1101  1001  0001  1111  0000  0010  1000  1010  1000  0000  0000  0000  0000  0000  0000  0000  0000  0010  0000  1111  0000  
B2AE4D91F061E8000000002058=>
1011  0010  1010  1110  0100  1101  1001  0001  1111  0000  0110  0001  1110  1000  0000  0000  0000  0000  0000  0000  0000  0000  0010  0000  0101  1000  
B2AE4D91F028E8000000002088=>
1011  0010  1010  1110  0100  1101  1001  0001  1111  0000  0010  1000  1110  1000  0000  0000  0000  0000  0000  0000  0000  0000  0010  0000  1000  1000  
B2AE4D91F06198000000002038=>1011  0010  1010  1110  0100  1101  1001  0001  1111  0000  0110  0001  1001  1000  0000  0000  0000  0000  0000  0000  0000  0000  0010  0000  0011  1000  

Please @AnalysIR Can you help me in Calculating Checksum, I have identified patterns for temperature, fan, modes etc but can not calculate Checksum. Can AnalysIR(Pro version) calculate all Checksum ? How many checksum algorithms does it support ? I am thinking of buying it.

**Comment by AnalysIR** [comment]
As this is not directly related to the library, please post your query over on our [IRForum](https://irforum.analysir.com/):

Make sure to post a set of RAW signals from 16degC to 30degC plus the on off signals (all in order and identified).
