### ISSUE TITLE
Try to use IRremote with PIN interruptions instead of polled based method

### ISSUE THREAD

**Issue by davidmans7** [z3t0/Arduino-IRremote#589]
**Board:** ARDUINO MEGA
**Library Version:** 2.2.3
**Protocol:** Mainly NEC, but I want to use all

**Code Block:**
https://gist.github.com/davidmans7/1e7c68c30281455445801ea7c4c8ea60

Hi!
I am trying to develop a sketch with Arduino that tries to guess Netflix/HBO/(any streaming video platform) passwords by sniffing IR codes from remote controllers.

The thing is that I'm using your library with standard use template (I mean by using _irrecv.decode(&results)_ and printing those data...). However, I want to know if it is possible to use interrumptions to manage the IR received data.

I want to do it in this manner because I am experiencing problems with repeated values, namely pressing once the key and receiving multiple data in Arduino.

I had found [this other library from Nico Hood](https://github.com/NicoHood/IRLremote) and following some YouTube tutorials ([mainly this one](https://www.youtube.com/watch?v=F_X0ZG2boo4&t=1014s)) I have just achieved my objective and now I can manage perfectly each button-press separately.
However, this Nico's library only supports NEC protocol and I saw that your library is quite more complete in this issue.

Thank you in advance!

**Comment by bengtmartensson** [comment]
There is already an issue on interruptdriven receptions, #439. 

Please have a look at my IR library, [Infrared](https://github.com/bengtmartensson/Infrared4Arduino). It implements capture using the "Data capture" pin/method. Note that you should use a non-demodulating receiver (like TSMP-58000)  if you really want to analyze the signal, lookung "under" the modulation -- IRremote cannot do this (I will look if Nico's can). Best way to use this is with the "high-level" sketch [AGirs](https://github.com/bengtmartensson/AGirs) together with the program [IrScrutinizer](https://github.com/bengtmartensson/harctoolboxbundle). Feedback welcome.
