### ISSUE TITLE
Impossible to use more than instance

### ISSUE THREAD

**Issue by tiludwig** [z3t0/Arduino-IRremote#600]
**Board:** GENERIC
**Library Version:** 2.1.0
**Protocol:** ALL

**checklist:**
- [x] I have **read** the README.md file thoroughly
- [x] I have searched existing issues to see if there is anything I have missed.
- [x] The latest [release](https://github.com/z3t0/Arduino-IRremote/releases/latest) is used
- [x] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here
- [x] The title of the issue is helpful and relevant 

Because the way it is implemented (using one global struct 'irparams') when you create more than one instance of IRrecv, the receive pin will be set to the last instance's receive pin. 

Please consider implementing your class as a Singleton, to make this more clear to the user.

**Comment by ArminJo** [comment]
Thank you for the hint.
