### ISSUE TITLE
Can I make a remote?

### ISSUE THREAD

**Issue by williamhmic** [z3t0/Arduino-IRremote#601]
Is it possible to make an actual remote with this? I want to be able to sort of make my own remote for a philips TV because.. Why not? :P Kind of just for practice. Can I use the code for this? Thank you and sorry if I am doing something wrong.

**Comment by AnalysIR** [comment]
Yes :)

Work thru the examples first and you should get a better idea.

**Comment by z3t0** [comment]
@williamhmic that's an excellent idea, and as @AnalysIR has mentioned it is entirely possibly.

I hope you have fun trying different encodings! Feel free to share the results of your project :smile:

**Comment by z3t0** [comment]
Closing for now, if you feel that this was done in error please do not hesitate to re-open the issue.
