### ISSUE TITLE
Issue with multiple definition of `__vector_13'

### ISSUE THREAD

**Issue by Oku1243** [z3t0/Arduino-IRremote#604]
**Board:** ARDUINO MEGA2560
**Library Version:** 2.2.3

it juste a little issue but i have  a error message taht say : 

 Arduino : 1.8.8 (Windows 10), Carte : "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Tone.cpp.o (symbol from plugin): In function `timer0_pin_port':

(.text+0x0): multiple definition of `__vector_13'

libraries\Arduino-IRremote-master\IRremote.cpp.o (symbol from plugin):(.text+0x0): first defined here

c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: Disabling relaxation: it will not work with multiple definitions

collect2.exe: error: ld returned 1 exit status

exit status 1
Erreur de compilation pour la carte Arduino/Genuino Mega or Mega 2560

**Comment by AnalysIR** [comment]
Difficult to comment without seeing your code!

Are you using any interrupts in your code that could be conflicting with IRremote?

Try to compile some of the examples provided.

**Comment by Oku1243** [comment]
this is my command

**Comment by Oku1243** [comment]
#include <Wire.h> // bibliothéque pour le I2C
#include <LiquidCrystal_I2C.h> // Pour l'ecrand Lcd avec I2C
#include <IRremote.h>
#include <dht.h>
#define DHT11_PIN 30
#define Recept_infra 9
#define ledRouge 3 // Constante pour la broche 3
#define ledVert 5 // Constante pour la broche 5
#define ledBleu 6 // Constante pour la broche 6
#define Son 31
dht DHT;

int pir = 33;               // choose the input pin (for PIR sensor)
int pirState = LOW;             // we start, assuming no motion detected
int val = 0;
int pwmRouge=0;
int pwmBleu=0;
int pwmVert=0;
int Led=0;
int Time=0;
int Lcd=1;
int Charg=2;

IRrecv Toto(Recept_infra);
decode_results message;
LiquidCrystal_I2C lcd(0x27, 2, 1, 0, 4 ,5, 6, 7, 3, POSITIVE); // déclare l'affiltation des broche
const int LCD_NB_ROWS = 2;
const int LCD_NB_COLUMNS = 16;

/*----------------------------Caractères personnalisés-------------------------------------------*/
byte START_DIV_0_OF_1[8] = {
  B01111, 
  B11000,
  B10000,
  B10000,
  B10000,
  B10000,
  B11000,
  B01111
}; // Char début 0 / 1

byte START_DIV_1_OF_1[8] = {
  B01111, 
  B11000,
  B10011,
  B10111,
  B10111,
  B10011,
  B11000,
  B01111
}; // Char début 1 / 1

byte DIV_0_OF_2[8] = {
  B11111, 
  B00000,
  B00000,
  B00000,
  B00000,
  B00000,
  B00000,
  B11111
}; // Char milieu 0 / 2

byte DIV_1_OF_2[8] = {
  B11111, 
  B00000,
  B11000,
  B11000,
  B11000,
  B11000,
  B00000,
  B11111
}; // Char milieu 1 / 2

byte DIV_2_OF_2[8] = {
  B11111, 
  B00000,
  B11011,
  B11011,
  B11011,
  B11011,
  B00000,
  B11111
}; // Char milieu 2 / 2

byte END_DIV_0_OF_1[8] = {
  B11110, 
  B00011,
  B00001,
  B00001,
  B00001,
  B00001,
  B00011,
  B11110
}; // Char fin 0 / 1

byte END_DIV_1_OF_1[8] = {
  B11110, 
  B00011,
  B11001,
  B11101,
  B11101,
  B11001,
  B00011,
  B11110
}; // Char fin 1 / 1


/**
 * Fonction de configuration de l'écran LCD pour la barre de progression.
 * Utilise les caractères personnalisés de 0 à 6 (7 reste disponible).
 */
void setup_progressbar() {

  /* Enregistre les caractères personnalisés dans la mémoire de l'écran LCD */
  lcd.createChar(0, START_DIV_0_OF_1);
  lcd.createChar(1, START_DIV_1_OF_1);
  lcd.createChar(2, DIV_0_OF_2);
  lcd.createChar(3, DIV_1_OF_2);
  lcd.createChar(4, DIV_2_OF_2);
  lcd.createChar(5, END_DIV_0_OF_1);
  lcd.createChar(6, END_DIV_1_OF_1);
}
/**
 * Fonction dessinant la barre de progression.
 *
 * @param percent Le pourcentage à afficher.
 */
void draw_progressbar(byte percent) {
 
  /* Affiche la nouvelle valeur sous forme numérique sur la première ligne */
  lcd.setCursor(0, 0);
  lcd.print(" Chargement ");
  lcd.print(percent);
  lcd.print(F("%  ")); 
  // N.B. Les deux espaces en fin de ligne permettent d'effacer les chiffres du pourcentage
  // précédent quand on passe d'une valeur à deux ou trois chiffres à une valeur à deux ou un chiffres.
 
  /* Déplace le curseur sur la seconde ligne */
  lcd.setCursor(0, 1);
 
  /* Map la plage (0 ~ 100) vers la plage (0 ~ LCD_NB_COLUMNS * 2 - 2) */
  byte nb_columns = map(percent, 0, 100, 0, LCD_NB_COLUMNS * 2 - 2);
  // Chaque caractère affiche 2 barres verticales, mais le premier et dernier caractère n'en affiche qu'une.

  /* Dessine chaque caractère de la ligne */
  for (byte i = 0; i < LCD_NB_COLUMNS; ++i) {

    if (i == 0) { // Premiére case

      /* Affiche le char de début en fonction du nombre de colonnes */
      if (nb_columns > 0) {
        lcd.write(1); // Char début 1 / 1
        nb_columns -= 1;

      } else {
        lcd.write((byte) 0); // Char début 0 / 1
      }

    } else if (i == LCD_NB_COLUMNS -1) { // Derniére case

      /* Affiche le char de fin en fonction du nombre de colonnes */
      if (nb_columns > 0) {
        lcd.write(6); // Char fin 1 / 1

      } else {
        lcd.write(5); // Char fin 0 / 1
      }

    } else { // Autres cases

      /* Affiche le char adéquat en fonction du nombre de colonnes */
      if (nb_columns >= 2) {
        lcd.write(4); // Char div 2 / 2
        nb_columns -= 2;

      } else if (nb_columns == 1) {
        lcd.write(3); // Char div 1 / 2
        nb_columns -= 1;

      } else {
        lcd.write(2); // Char div 0 / 2
      }
    }
  }
}



 //---------------Programme-------------------------------
 
void setup () // ouvre la boucle
  {
     lcd.begin(LCD_NB_COLUMNS, LCD_NB_ROWS);
     setup_progressbar();
     lcd.clear();
     pinMode (ledVert,OUTPUT);
     pinMode (ledRouge,OUTPUT);
     pinMode (ledBleu,OUTPUT);
     pinMode (Son,OUTPUT);
     Toto.enableIRIn();
     Toto.blink13(true);
     Serial.begin(9600);
  }

  void loop () {
      Start ();
      Led_Task ();
      Task_PC ();
      Task_IRremote ();
      Task_DHT11 ();
      Time=0;
  }
void Start () {
  if (Charg==2){
      pwmVert=0;
      pwmRouge=255;
      pwmBleu=0;
      analogWrite(ledRouge, pwmRouge);
      analogWrite(ledVert, pwmVert);
      analogWrite(ledBleu, pwmBleu);
      while (Time != 7){
        Charg=0;
        Lcd=3;
        lcd.setCursor(0,0);
        lcd.print("   Demmarage.");
        delay(500);
        lcd.clear();
        lcd.setCursor(0,0);
        lcd.print("   Demmarage..");
        delay(500);
        lcd.clear();
        lcd.setCursor(0,0);
        lcd.print("   Demmarage...");
        delay(500);
        lcd.clear();
        Time ++ ;
        }
    }
      if (Time==7){
        Time=0;
        Charg=1;
        pwmVert=137;
        pwmRouge=51;
        pwmBleu=232;
        analogWrite(ledRouge, pwmRouge);
        analogWrite(ledVert, pwmVert);
        analogWrite(ledBleu, pwmBleu);
    }
       /* Valeur en pourcentage de la barre de progression */
  if (Charg==1) {
  static byte percent = 0;
 
  /* Affiche la valeur */
  draw_progressbar(percent);

  /* Incrémente le pourcentage */
  if (++percent == 101) {
    // Revient à zéro si le pourcentage dépasse 100%
    percent = 0;
    delay(1000);
    lcd.clear(); // essuie l'ecran
     lcd.setCursor(0,0); // Place le curseur a la ligne 1
     lcd.print("Message du pc:");  // met le texte sur la ligne 1
     lcd.setCursor(0,1); // met le curseur sur la ligne 2
     lcd.print("     RIEN");  // met le texte sur la ligne 1
    Charg=0;
  }

  /* Petit temps d'attente */
  delay(50);
  if (Charg==0) {
    Lcd=1;
  }
  }
}

void Task_PC() {
  if (Serial.available()) 
        {
          Charg=1;
           while(Led != 10) 
          {
                pwmVert=0;
                pwmRouge=0;
                pwmBleu=255;
                analogWrite(ledRouge, pwmRouge);
                analogWrite(ledVert, pwmVert);
                analogWrite(ledBleu, pwmBleu);
                digitalWrite(Son, HIGH);
                delay(100);
                digitalWrite(Son, LOW);
                delay(200);
                pwmVert=0;
                pwmRouge=0;
                pwmBleu=0;
                analogWrite(ledRouge, pwmRouge);
                analogWrite(ledVert, pwmVert);
                analogWrite(ledBleu, pwmBleu);
                delay(200);
                Led ++ ; 
          }
           pwmVert=255;
           pwmRouge=255;
           pwmBleu=0;
           analogWrite(ledRouge, pwmRouge);
           analogWrite(ledVert, pwmVert);
           analogWrite(ledBleu, pwmBleu);
          while(Charg != 0) {
                   /* Valeur en pourcentage de la barre de progression */
  if (Charg==1) {
  static byte percent = 0;
 
  /* Affiche la valeur */
  draw_progressbar(percent);

  /* Incrémente le pourcentage */
  if (++percent == 101) {
    // Revient à zéro si le pourcentage dépasse 100%
    percent = 0;
    delay(1000);
    lcd.clear(); // essuie l'ecran
     lcd.setCursor(0,0); // Place le curseur a la ligne 1
     lcd.print("Message du pc:");  // met le texte sur la ligne 1
     lcd.setCursor(0,1); // met le curseur sur la ligne 2
     lcd.print("     RIEN");  // met le texte sur la ligne 1
    Charg=0;
  }

  /* Petit temps d'attente */
  delay(50);
  Lcd=3;
  if (Charg==0) {
    Lcd=1;
  }
  }
          }
           delay(200);
           lcd.clear(); 
           lcd.setCursor(16,0);
           lcd.write("Message du pc:");  
           lcd.setCursor(16,1);
           while (Serial.available() >0)
           {
            lcd.write(Serial.read());
           }
           Serial.println("Message envoyé");
           Led=0;
           pwmVert=255;
           pwmRouge=0;
           pwmBleu=0;
           analogWrite(ledRouge, pwmRouge);
           analogWrite(ledVert, pwmVert);
           analogWrite(ledBleu, pwmBleu);
           //tone(Son, 500, 100);
        }
}

void Task_IRremote () {
  if (Toto.decode(&message)) {
        digitalWrite(Son, HIGH);
        delay(100);
        digitalWrite(Son, LOW);
        if (message.value == 0xFF30CF){
          lcd.setCursor(1,0);
          lcd.clear();
          lcd.write("Message recu!");
          Charg=1;
          while(Led != 10) 
          {
                pwmVert=0;
                pwmRouge=0;
                pwmBleu=255;
                analogWrite(ledRouge, pwmRouge);
                analogWrite(ledVert, pwmVert);
                analogWrite(ledBleu, pwmBleu);
                //tone(Son, 500, 100);
                delay(200);
                pwmVert=0;
                pwmRouge=0;
                pwmBleu=0;
                analogWrite(ledRouge, pwmRouge);
                analogWrite(ledVert, pwmVert);
                analogWrite(ledBleu, pwmBleu);
                delay(200);
                Led ++ ; 
          }
           pwmVert=255;
           pwmRouge=255;
           pwmBleu=0;
           analogWrite(ledRouge, pwmRouge);
           analogWrite(ledVert, pwmVert);
           analogWrite(ledBleu, pwmBleu);
          while(Charg != 0) {
                   /* Valeur en pourcentage de la barre de progression */
  if (Charg==1) {
  static byte percent = 0;
 
  /* Affiche la valeur */
  draw_progressbar(percent);

  /* Incrémente le pourcentage */
  if (++percent == 101) {
    // Revient à zéro si le pourcentage dépasse 100%
    percent = 0;
    delay(1000);
    lcd.clear(); // essuie l'ecran
     lcd.setCursor(0,0); // Place le curseur a la ligne 1
     lcd.print("Message du pc:");  // met le texte sur la ligne 1
     lcd.setCursor(0,1); // met le curseur sur la ligne 2
     lcd.print("     RIEN");  // met le texte sur la ligne 1
    Charg=0;
  }

  /* Petit temps d'attente */
  delay(50);
  Lcd=3;
  if (Charg==0) {
    Lcd=1;
  }
  }
          }
           Lcd=1;
           delay(200); 
           lcd.clear(); 
           lcd.setCursor(16,0);
           lcd.write("Message envoye:");  
           lcd.setCursor(16,1);
           lcd.write("Ceci marche! <3");
           Serial.println("Message envoye");
           Led=0;
           pwmVert=255;
           pwmRouge=0;
           pwmBleu=0;
           analogWrite(ledRouge, pwmRouge);
           analogWrite(ledVert, pwmVert);
           analogWrite(ledBleu, pwmBleu);
           digitalWrite(Son, HIGH);
           delay(100);
           digitalWrite(Son, LOW);
           //tone(Son, 500, 100);
           Toto.resume();
        }
        if (message.value == 0xFF18E7){
          lcd.setCursor(1,0);
          lcd.clear();
          lcd.write("Message recu!");
          Charg=1;
          while(Led != 10) 
          {
                pwmVert=0;
                pwmRouge=0;
                pwmBleu=255;
                analogWrite(ledRouge, pwmRouge);
                analogWrite(ledVert, pwmVert);
                analogWrite(ledBleu, pwmBleu);
                delay(200);
                pwmVert=0;
                pwmRouge=0;
                pwmBleu=0;
                analogWrite(ledRouge, pwmRouge);
                analogWrite(ledVert, pwmVert);
                analogWrite(ledBleu, pwmBleu);
                /* Valeur en pourcentage de la barre de progression */
                delay(200);
                Led ++ ; 
          }
          pwmVert=255;
           pwmRouge=255;
           pwmBleu=0;
           analogWrite(ledRouge, pwmRouge);
           analogWrite(ledVert, pwmVert);
           analogWrite(ledBleu, pwmBleu);
          while(Charg != 0) {
                   /* Valeur en pourcentage de la barre de progression */
  if (Charg==1) {
  static byte percent = 0;
 
  /* Affiche la valeur */
  draw_progressbar(percent);

  /* Incrémente le pourcentage */
  if (++percent == 101) {
    // Revient à zéro si le pourcentage dépasse 100%
    percent = 0;
    delay(1000);
    lcd.clear(); // essuie l'ecran
     lcd.setCursor(0,0); // Place le curseur a la ligne 1
     lcd.print("Message du pc:");  // met le texte sur la ligne 1
     lcd.setCursor(0,1); // met le curseur sur la ligne 2
     lcd.print("     RIEN");  // met le texte sur la ligne 1
    Charg=0;
  }

  /* Petit temps d'attente */
  delay(50);
  Lcd=3;
  if (Charg==0) {
    Lcd=1;
  }
  }
          }
           Lcd=0;
           lcd.clear();
           Led=0;
           pwmVert=255;
           pwmRouge=0;
           pwmBleu=0;
           analogWrite(ledRouge, pwmRouge);
           analogWrite(ledVert, pwmVert);
           analogWrite(ledBleu, pwmBleu);
           digitalWrite(Son, HIGH);
           delay(100);
           digitalWrite(Son, LOW);
           Toto.resume();
        }
        if (message.value == 0xFF7A85){
          lcd.setCursor(1,0);
          lcd.clear();
          lcd.write("Message recu!");
          while(Led != 10) 
          {
                pwmVert=0;
                pwmRouge=0;
                pwmBleu=255;
                analogWrite(ledRouge, pwmRouge);
                analogWrite(ledVert, pwmVert);
                analogWrite(ledBleu, pwmBleu);
                delay(200);
                pwmVert=0;
                pwmRouge=0;
                pwmBleu=0;
                analogWrite(ledRouge, pwmRouge);
                analogWrite(ledVert, pwmVert);
                analogWrite(ledBleu, pwmBleu);
                delay(200);
                Led ++ ; 
          }
           Lcd=1;
           delay(200); 
           lcd.clear(); 
           lcd.setCursor(16,0);
           lcd.write("Message envoye:");  
           lcd.setCursor(16,1);
           lcd.write("Best parents ever <3");
           Serial.println("Message envoye");
           Led=0;
           pwmVert=255;
           pwmRouge=0;
           pwmBleu=0;
           analogWrite(ledRouge, pwmRouge);
           analogWrite(ledVert, pwmVert);
           analogWrite(ledBleu, pwmBleu);
           digitalWrite(Son, HIGH);
           delay(100);
           digitalWrite(Son, LOW);
           Toto.resume();
        }
        Toto.resume();
      }
}

void Led_Task () {
  if (pwmVert==255){
    Time=0;
        while(Time != 10) 
        {
          Time ++ ;
          delay(500);
          if (Lcd==1){
          lcd.scrollDisplayLeft();
            
          
          }
        }
      }
      if (Time==10){
           pwmVert=137;
           pwmRouge=51;
           pwmBleu=232;
           analogWrite(ledRouge, pwmRouge);
           analogWrite(ledVert, pwmVert);
           analogWrite(ledBleu, pwmBleu);
          }
      analogWrite(ledRouge, pwmRouge);
      analogWrite(ledVert, pwmVert);
      analogWrite(ledBleu, pwmBleu);
}

void Task_DHT11 () {
  if (Lcd==1){
      lcd.scrollDisplayLeft();
      delay(500);
      }
      if (Lcd==0){
        int chk = DHT.read11(DHT11_PIN);
        lcd.setCursor(0,0); 
           lcd.print("Temp: ");
           lcd.print(DHT.temperature);
           lcd.print((char)223);
           lcd.print("C");
           lcd.setCursor(0,1);
           lcd.print("Humidity: ");
           lcd.print(DHT.humidity);
           lcd.print("%");
           Time=0;
        delay(1200);
      }
}

**Comment by Oku1243** [comment]
it work if i dont use the command tone

**Comment by AnalysIR** [comment]
Sounds like a timer conflict...but not obvious..

Try changing the pin you are using to receive IR. try 10 different spare pins around the Arduino

**Comment by AnalysIR** [comment]
..and..please put the code you posted inside code tags "<>2 in the edit menu

**Comment by ArminJo** [comment]
Try other IR timers. You can change it [here](https://github.com/z3t0/Arduino-IRremote/blob/8f665d60f065c139bf641a152518b078bec84437/src/private/IRremoteBoardDefs.h#L186)
