### ISSUE TITLE
Change of ir send pin

### ISSUE THREAD

**Issue by anshchawla521** [z3t0/Arduino-IRremote#613]
**Board:** ARDUINO pro mini
**Library Version:** 2.4.0
**Protocol:** nec(if any)
 I want to change the IR transmit pin from pin 3 to 9 which lines do I have to edit in boards.h file

**Comment by AnalysIR** [comment]
in [boardefs.h](https://github.com/z3t0/Arduino-IRremote/blob/master/boarddefs.h) change the following at line 149 _(valid as of 6th march 2019 / master)_

```
#else
// Arduino Duemilanove, Diecimila, LilyPad, Mini, Fio, Nano, etc
// ATmega48, ATmega88, ATmega168, ATmega328
	//#define IR_USE_TIMER1   // tx = pin 9
	#define IR_USE_TIMER2     // tx = pin 3

#endif

```

to 

```
#else
// Arduino Duemilanove, Diecimila, LilyPad, Mini, Fio, Nano, etc
// ATmega48, ATmega88, ATmega168, ATmega328
	#define IR_USE_TIMER1   // tx = pin 9
	//#define IR_USE_TIMER2     // tx = pin 3

#endif
```
