### ISSUE TITLE
Нужен простой скетч

### ISSUE THREAD

**Issue by toll101** [z3t0/Arduino-IRremote#621]
Дорогие друзья, помогите решить такую задачу: Есть необходимость по команде (внешняя кнопка - например) включить шаговый двигатель. После выполнения заданного числа оборотов (1000) остановить его и включить второй шаговый двигатель с аналогичной задачей (допустим 2000 оборотов). После получения второй команды программа отрабатывает все в обратном порядке. Сначала второй мотор 2000 оборотов в обратном направлении, затем первый. Оба двигателя должны выдавать по 50 Вт мощности. То есть необходимы достаточно мощные контроллеры. На данный момент есть плата Ардуино уно, и два двигателя 42 серии. 
Нужны рекомендации по контроллерам, схема соединения Ардуино, контроллеров, кнопок управления и двигателей. И, конечно скетч программы.

**Comment by AnalysIR** [comment]
not related to the IRremote library, please close.

**Comment by toll101** [comment]
Я правильно понял, вы не можете мне помочь?
Задача, мне кажется очень простой, для программиста...
Вопросы подбора элементной базы я уже решил.
Нужна только программа для ардуино. 
С уважением и наилучшими пожеланиями.

**Comment by AnalysIR** [comment]
You are correct, this is the wrong place for this issue.

maybe try the Arduino forum (Russian Section) via
[Россия - Russia](https://forum.arduino.cc/index.php?board=120.0)

Please close the issue
