### ISSUE TITLE
how can ir reciever with attiny85? (what pin should i connect the reciever to)

### ISSUE THREAD

**Issue by Mustafa744** [z3t0/Arduino-IRremote#622]
Board: Attiny 85
Library Version: 2.1.0
Protocol: any

**Code Block:
//regular recuever code

**checklist:**
- [✓] I have **read** the README.md file thoroughly
- [✓] I have searched existing issues to see if there is anything I have missed.
- [] The latest [release](https://github.com/z3t0/Arduino-IRremote/releases/latest) is used
- [] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here
- [✓] The title of the issue is helpful and relevant

**Comment by AnalysIR** [comment]
Any available GPIO pin.
