### ISSUE TITLE
how do i send protocol 12

### ISSUE THREAD

**Issue by Japie3krekel** [z3t0/Arduino-IRremote#632]
**Board:** ARDUINO NANO
**Library Version:** 2.1.0
**Protocol:** 12

Hello when I use the irrecord script from the library  it says that the protocol is 12.
Can someone help me find out which protocol that is. And how i can send it??

**Comment by AnalysIR** [comment]
It may be **Mitsubishi**

However, a better example sketch to use may be **IRrecvdumpv2** in the examples folder.

You can use this output to send using **sendRAW** or possible

If this is a Mitsubishi signal, there is no native support for sending...so **sendRAW** is the best option for now.

**Comment by Japie3krekel** [comment]
ok thanks ill try that
