### ISSUE TITLE
sendraw sends inaccurate codes

### ISSUE THREAD

**Issue by Japie3krekel** [z3t0/Arduino-IRremote#634]
**Board:** ARDUINO nano
**Library Version:** 2.1.0
**Protocol:** Sony (if any)

when i sendc raw codes to my tv it sends the wrong codes
this is the code i try to send
unsigned int uitnieuw[33] = {250, 2200, 250, 2150, 250, 2100, 250, 1000, 250, 1000, 200, 950, 250, 2150, 250, 950, 250, 950, 250, 2150, 250, 950, 200, 1000, 250, 900, 300, 900, 250, 1000, 250, 950, 250};

but i receive different codes with my receiver how can i fix this ??

**Comment by AnalysIR** [comment]
It decodes on our AnalysIR application as Mitsubishi.
The nature of the protocol timings means that any innacuracy introduced by the IR receiver & IRremote can be material.

Using AnalysIR, I cleaned it up and generated the following code for IRremote.
```
/*
Automatically Generated by AnalysIR - Batch Export Utility
Registered to: xxxxxxxx
Session History
Type : Key : Value : Bits : Carrier Frequency (kHz)
0 : MITSUBISHI8TV :  : E240 : 16 : 0
Note: Be sure to use the correct Carrier frequency, for each individual signal, as(or if) indicated above
*/

// NB: Not all protocols are supported by IRremote or IRLib. You may need to edit the code below manually
// Automatically Generated by AnalysIR for xxxxxxxx, visit https://www.AnalysIR.com/ or email info@....... for further details
int khz=38; //NB Change this default value as neccessary to the correct carrier frequency


unsigned int Signal_0_0[] = {300,2100,300,2100,300,2100,300,900,300,900,300,900,300,2100,300,900,300,900,300,2100,300,900,300,900,300,900,300,900,300,900,300,900,300}; //AnalysIR Batch Export (IRremote) - RAW

irsend.sendRaw(Signal_0_0, sizeof(Signal_0_0)/sizeof(int), khz); //AnalysIR Batch Export (IRremote) - RAW
 // AnalysIR IR Protocol: MITSUBISHI8TV, Key:  

```
So try changing the timings for your other signals as above.
