### ISSUE TITLE
Readme Installation Wording Confusion

### ISSUE THREAD

**Issue by jerryjeremiah** [z3t0/Arduino-IRremote#636]
The wording in the installation section of the readme is a bit confusing.

This line refers to the libraries directory without actually saying which one or where to find it:

4. Move the "IRremote" folder that has been extracted to your libraries directory.

But the next line actually does explain it really well by saying "Arduino_Root/libraries/ ... Where Arduino_Root refers to the install directory of Arduino" 

Could it be reworded so that step 4 has a good description of where the libraries directory actually is?

I am suggesting this because of a discussion at:

https://stackoverflow.com/questions/56781065/irremote-h-no-such-file-or-directory/56783020#56783020

**Comment by ArminJo** [comment]
Fixed in current version
