### ISSUE TITLE
Library will NOT compile on the UNO WiFi Rev 2

### ISSUE THREAD

**Issue by cpapir** [z3t0/Arduino-IRremote#641]
**Board:** ARDUINO UNO WiFi Rev 2
**Library Version:** Version - 2.2.3
**Protocol:**  ALL

Options:
Board: Arduino Uno WiFi Rev 2
Register Emulation: None(ATMEGA4098)
Programer: Onboard Atmel mEDBG(UNO WiFi Rev 2)

**Code Block:**
#include <IRremote.h>
void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}

Compiler errors:
Arduino: 1.8.10 Hourly Build 2019/05/21 09:33 (Windows 10), Board: "Arduino Uno WiFi Rev2, None (ATMEGA4809)"

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp: In member function 'void IRrecv::enableIRIn()':

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:192:3: error: 'TCCR2A' was not declared in this scope

   TCCR2A = _BV(WGM21); \

   ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp: In member function 'void IRsend::mark(unsigned int)':

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:166:30: error: 'TCCR2A' was not declared in this scope

 #define TIMER_ENABLE_PWM    (TCCR2A |= _BV(COM2B1))

                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:24:2: note: in expansion of macro 'TIMER_ENABLE_PWM'

  TIMER_ENABLE_PWM; // Enable pin 3 PWM output

  ^~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:192:3: note: suggested alternative: 'TCB2'

   TCCR2A = _BV(WGM21); \

   ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

In file included from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:99:0,

                 from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/String.h:30,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Print.h:24,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Stream.h:25,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Client.h:22,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/Arduino.h:23,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:192:16: error: 'WGM21' was not declared in this scope

   TCCR2A = _BV(WGM21); \

                ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:166:30: note: suggested alternative: 'TCB2'

 #define TIMER_ENABLE_PWM    (TCCR2A |= _BV(COM2B1))

                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:24:2: note: in expansion of macro 'TIMER_ENABLE_PWM'

  TIMER_ENABLE_PWM; // Enable pin 3 PWM output

  ^~~~~~~~~~~~~~~~

In file included from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:99:0,

                 from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/String.h:30,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Print.h:24,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Stream.h:25,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Client.h:22,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/Arduino.h:23,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:166:44: error: 'COM2B1' was not declared in this scope

 #define TIMER_ENABLE_PWM    (TCCR2A |= _BV(COM2B1))

                                            ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:24:2: note: in expansion of macro 'TIMER_ENABLE_PWM'

  TIMER_ENABLE_PWM; // Enable pin 3 PWM output

  ^~~~~~~~~~~~~~~~

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:193:3: error: 'TCCR2B' was not declared in this scope

   TCCR2B = _BV(CS21); \

   ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:193:3: note: suggested alternative: 'TCB2'

   TCCR2B = _BV(CS21); \

   ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

In file included from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:99:0,

                 from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/String.h:30,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Print.h:24,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Stream.h:25,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Client.h:22,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/Arduino.h:23,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:193:16: error: 'CS21' was not declared in this scope

   TCCR2B = _BV(CS21); \

                ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:194:3: error: 'OCR2A' was not declared in this scope

   OCR2A  = TIMER_COUNT_TOP / 8; \

   ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:195:3: error: 'TCNT2' was not declared in this scope

   TCNT2  = 0; \

   ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp: In member function 'void IRsend::space(unsigned int)':

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:167:30: error: 'TCCR2A' was not declared in this scope

 #define TIMER_DISABLE_PWM   (TCCR2A &= ~(_BV(COM2B1)))

                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:35:2: note: in expansion of macro 'TIMER_DISABLE_PWM'

  TIMER_DISABLE_PWM; // Disable pin 3 PWM output

  ^~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:195:3: note: suggested alternative: 'TCB2'

   TCNT2  = 0; \

   ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:141:2: note: in expansion of macro 'TIMER_CONFIG_NORMAL'

  TIMER_CONFIG_NORMAL();

  ^~~~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:168:30: error: 'TIMSK2' was not declared in this scope

 #define TIMER_ENABLE_INTR   (TIMSK2 = _BV(OCIE2A))

                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:144:2: note: in expansion of macro 'TIMER_ENABLE_INTR'

  TIMER_ENABLE_INTR;

  ^~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:167:30: note: suggested alternative: 'TCB2'

 #define TIMER_DISABLE_PWM   (TCCR2A &= ~(_BV(COM2B1)))

                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:35:2: note: in expansion of macro 'TIMER_DISABLE_PWM'

  TIMER_DISABLE_PWM; // Disable pin 3 PWM output

  ^~~~~~~~~~~~~~~~~

In file included from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:99:0,

                 from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/String.h:30,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Print.h:24,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Stream.h:25,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Client.h:22,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/Arduino.h:23,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:167:46: error: 'COM2B1' was not declared in this scope

 #define TIMER_DISABLE_PWM   (TCCR2A &= ~(_BV(COM2B1)))

                                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:35:2: note: in expansion of macro 'TIMER_DISABLE_PWM'

  TIMER_DISABLE_PWM; // Disable pin 3 PWM output

  ^~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:168:30: note: suggested alternative: 'TIMERB2'

 #define TIMER_ENABLE_INTR   (TIMSK2 = _BV(OCIE2A))

                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:144:2: note: in expansion of macro 'TIMER_ENABLE_INTR'

  TIMER_ENABLE_INTR;

  ^~~~~~~~~~~~~~~~~

In file included from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:99:0,

                 from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/String.h:30,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Print.h:24,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Stream.h:25,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Client.h:22,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/Arduino.h:23,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:168:43: error: 'OCIE2A' was not declared in this scope

 #define TIMER_ENABLE_INTR   (TIMSK2 = _BV(OCIE2A))

                                           ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irRecv.cpp:144:2: note: in expansion of macro 'TIMER_ENABLE_INTR'

  TIMER_ENABLE_INTR;

  ^~~~~~~~~~~~~~~~~

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp: In member function 'void IRsend::enableIROut(int)':

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:169:30: error: 'TIMSK2' was not declared in this scope

 #define TIMER_DISABLE_INTR  (TIMSK2 = 0)

                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:60:2: note: in expansion of macro 'TIMER_DISABLE_INTR'

  TIMER_DISABLE_INTR; //Timer2 Overflow Interrupt

  ^~~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:169:30: note: suggested alternative: 'TIMERB2'

 #define TIMER_DISABLE_INTR  (TIMSK2 = 0)

                              ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:60:2: note: in expansion of macro 'TIMER_DISABLE_INTR'

  TIMER_DISABLE_INTR; //Timer2 Overflow Interrupt

  ^~~~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:174:2: error: 'TCCR2A' was not declared in this scope

  TCCR2A               = _BV(WGM20); \

  ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:174:2: note: suggested alternative: 'TCB2'

  TCCR2A               = _BV(WGM20); \

  ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

In file included from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:99:0,

                 from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/String.h:30,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Print.h:24,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Stream.h:25,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Client.h:22,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/Arduino.h:23,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:174:29: error: 'WGM20' was not declared in this scope

  TCCR2A               = _BV(WGM20); \

                             ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:175:2: error: 'TCCR2B' was not declared in this scope

  TCCR2B               = _BV(WGM22) | _BV(CS20); \

  ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:175:2: note: suggested alternative: 'TCB2'

  TCCR2B               = _BV(WGM22) | _BV(CS20); \

  ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

In file included from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\io.h:99:0,

                 from c:\users\papirc\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5\avr\include\avr\pgmspace.h:90,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/String.h:30,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Print.h:24,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Stream.h:25,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/Client.h:22,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/api/ArduinoAPI.h:29,

                 from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/Arduino.h:23,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:175:29: error: 'WGM22' was not declared in this scope

  TCCR2B               = _BV(WGM22) | _BV(CS20); \

                             ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:175:42: error: 'CS20' was not declared in this scope

  TCCR2B               = _BV(WGM22) | _BV(CS20); \

                                          ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:1:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:176:2: error: 'OCR2A' was not declared in this scope

  OCR2A                = pwmval; \

  ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:177:2: error: 'OCR2B' was not declared in this scope

  OCR2B                = pwmval / 3; \

  ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\irSend.cpp:70:2: note: in expansion of macro 'TIMER_CONFIG_KHZ'

  TIMER_CONFIG_KHZ(khz);

  ^~~~~~~~~~~~~~~~

exit status 1
In file included from C:\Users\papirc\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.1\cores\arduino/Arduino.h:27:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.cpp:23:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.cpp: In function 'void TIMER2_COMPA_vect()':

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:170:29: warning: 'TIMER2_COMPA_vect' appears to be a misspelled 'signal' handler, missing '__vector' prefix [-Wmisspelled-isr]

 #define TIMER_INTR_NAME     TIMER2_COMPA_vect

                             ^

C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.cpp:129:6: note: in expansion of macro 'TIMER_INTR_NAME'

 ISR (TIMER_INTR_NAME)

      ^~~~~~~~~~~~~~~

In file included from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremoteInt.h:111:0,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.h:24,

                 from C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.cpp:23:

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:51:32: error: no match for 'operator|=' (operand types are 'PORT_t {aka PORT_struct}' and 'int')

 # define BLINKLED_ON()  (PORTB |= B00100000)

C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.cpp:196:10: note: in expansion of macro 'BLINKLED_ON'

     else BLINKLED_ON() ;   // if no user defined LED pin, turn default LED pin for the hardware on

          ^~~~~~~~~~~

C:\Users\papirc\Documents\Arduino\libraries\IRremote\boarddefs.h:52:33: error: no match for 'operator&=' (operand types are 'PORT_t {aka PORT_struct}' and 'int')

 # define BLINKLED_OFF()  (PORTB &= B11011111)

C:\Users\papirc\Documents\Arduino\libraries\IRremote\IRremote.cpp:198:10: note: in expansion of macro 'BLINKLED_OFF'

     else BLINKLED_OFF() ;   // if no user defined LED pin, turn default LED pin for the hardware on

          ^~~~~~~~~~~~

Error compiling for board Arduino Uno WiFi Rev2.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by AnalysIR** [comment]
Yes, this is to be expected.

...because this board uses the ATMEGA4809, it is not currently supported.

Hopefully, over time someone (who has this bord) will contribute support for this newer platform. There are a few similar boards that have been released in the last few months. It should be relatively easy to add support.

The README for the library, lists the Boards/Platforms/MCUs that do have support.

**Comment by cpapir** [comment]
I am trying to implement an IR remote control on a UNO wifi rev 2 can you suggest any one or anywhere I can get some help?

**Comment by AnalysIR** [comment]
I am not aware of anyone working on those new platforms yet, for IR.

You could ask the manufacturer/Seller for support or post on the Arduino forum.

I would normally suggest our own IRForum, but we dont have any ATMEGA4809 platforms available yet.

It should only be a small amount of code for anyone with the platform.

**Comment by ArminJo** [comment]
ATMEGA4809 is now supported.
