### ISSUE TITLE
Arduino motors & IR remote

### ISSUE THREAD

**Issue by CrazyAlissa** [z3t0/Arduino-IRremote#644]
Hello, so I am doing a project with a robot and Arduino. I have some LEDs, the Arduino Uno, IR remote and a sheild for motors. I use multithreading for the remote and LEDs and with the remote I control the motors to move forward, backwards, left and right. The only problem is that when I need to go forward the right side of the motors only work at maximum (255), so I can't accelerate. And I know is a problem with the Ir but i doesn't know what to do. 
The Rover library is just the library that give the motors the speed. 
My motors are attached to pins 3,5,6,9. I use Arduino Uno, and a motor sheild L298
I think the problem is that i have a motor on pin 3 and  the timer that is used for this library is 3 too. But my sheild is made for that pin and i dont know how to change the timer.

**Comment by ArminJo** [comment]
Do you really need 4 independent motor speeds? Try to use 2 motors at one pin, to get pin 3 free.
