### ISSUE TITLE
support for mkrzero arduino (samd21 based)

### ISSUE THREAD

**Issue by JavaMan7** [z3t0/Arduino-IRremote#650]
Board:  mkrzero arduino
Library Version: 2.1.0

mkrzero is powerful arduino with a 32bit arm core processor this device can be used for high quality  audio playback and many more applications. Adding IR capabilities to this bored would open so many possibilities.

**Comment by ArminJo** [comment]
SAMD support is now available and also supported by [IRMP](https://github.com/ukw100/IRMP)
