### ISSUE TITLE
Europe

### ISSUE THREAD

**Issue by draxaris1010** [z3t0/Arduino-IRremote#656]
**Board:** Makeblock mCore(Arduino Uno Plus)
**Library Version:** 2.1.0
**Protocol:** Sony (if any)

There is a problem with European remote controllers it can not decode any of those signals.

**checklist:**
- [x] I have **read** the README.md file thoroughly
- [x] I have searched existing issues to see if there is anything I have missed.
- [x] The latest [release](https://github.com/z3t0/Arduino-IRremote/releases/latest) is used
- [x] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here
- [x] The title of the issue is helpful and relevant 

** We will start to close issues that do not follow these guidelines as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

The above is a short template allowing you to make detailed issues!

**Comment by AnalysIR** [comment]
> There is a problem with European remote controllers it can not decode any of those signals.

Your assumption is incorrect. More likely an issue with your approach.


> The title of the issue is helpful and relevant

Your tiltle is not very helpful...
