### ISSUE TITLE
Support for Nano 33 IoT and other SAMD based boards

### ISSUE THREAD

**Issue by eclipse1985** [z3t0/Arduino-IRremote#663]
Just tested this library with a Nano 33 IoT board, it works like a charm!

Can you please add details (ex. PIN) in the README?

**Comment by magdyabdel** [comment]
I seem to be having issues compiling the IRSendDemo for **Nano 33 BLE Sense**. Is there anything specific you did?

I get this error:
`~\Arduino\libraries\IRremote\IRremote.cpp:21:10: fatal error: avr/interrupt.h: No such file or directory`

**Comment by eclipse1985** [comment]
Nano IoT microcontroller is different from the Nano BLE
