### ISSUE TITLE
SparkFun Pro Micro - IRSend leaves IR LED in on state

### ISSUE THREAD

**Issue by noenthu** [z3t0/Arduino-IRremote#666]
**Board:** SparkFun Pro Micro 5
**Library Version:** 2.2.3
**Protocol:** Any

**Code Block:**
```c

#include <IRremote.h>

IRsend irsend;

void setup()
{
}

void loop() {
	for (int i = 0; i < 3; i++) {
		irsend.sendSony(0xa90, 12);
                Serial.println(i);
		delay(40);
	}
	delay(5000); //5 second delay between each signal burst
}

```

I have followed some of the recommendations when using the Spark Fun Pro Micro (5v/16Hz) board. Including..
- Updated to use timer3
- Updated to use pin 5 for output

What I observe when running above code, the onboard Tx LED blinks 3 times (likely during the Serial output) and then repeats every 5 seconds. The IR LED stays in an "on" state (verified by using cellphone camera).

**Comment by noenthu** [comment]
Lucky #666

**Comment by ArminJo** [comment]
Did you set the pin before to OUTPUT or INPUT_PULLUP, or connect IR-LED to VCC?
