### ISSUE TITLE
Support STM8S003

### ISSUE THREAD

**Issue by hahuyquyen** [z3t0/Arduino-IRremote#667]
Hi all,
I use STM8S003F3P6 adruino core ( sduino library).  I use IRremote library but have problem about interrupt. The compiler Adruino IDE inform no such file <avr/interrupt.h>. I know to use IRremote libray need to modify a little bit but my knowlegde about this MCU not enough. Anyone can support me?

**Comment by ArminJo** [comment]
You must code it by yourself or look for forks, where it has already been done.
