### ISSUE TITLE
atmega 328 frequency problem/question

### ISSUE THREAD

**Issue by nedoskiv** [z3t0/Arduino-IRremote#668]
Hello,

I wrote remote control (receiver)  sketch on arduino UNO all works fine, then decided to move whole thing on just an atmega 328p processor using his internal clock , on 8MHz nothing works, on 1MHz few buttons are recognized.
My question is does processor frequency affect stability of irreceiver? If yes, I can use an external escilator, what frequency is  considered stable?

**Comment by AnalysIR** [comment]
If possible, use a crystal or resonator @ 16 or 8 or 4 Mhz (higher is better)

Without a crystal, it is possibe to calibrate the internal clock...I would stick with 8Mhz for this.
Do a search on how to calibrate the internal oscillator.

I expect you will see lots of issues @ 1MHz with or without a crystal.

**Comment by nedoskiv** [comment]
On other devices when uart is needed i use 18.432MHz and work fine, gonna try it here too and post results

**Comment by AnalysIR** [comment]
FYI: IRremote depends on the Arduino timers. e.g. Timer0, Timer1or2, micros() etc

I don't believe 18.432MHz is supported by Arduino for UNO.

**Conclusion**: I would be surprised if it worked without modifications.

**Comment by nedoskiv** [comment]
just attached 18.432 MHz external oscilator and everything works fine

**Comment by AnalysIR** [comment]
Very interesting result indeed ...  can you post the code you use to record signals and the code you use send signals.(along with the oscillator used)

What BAUD rate are you using for Serial using the "18.432 MHz external oscillator" ?

Have you modified the Arduino Board definitiions or core for that crystal speed. If the UNO is configured for 16Mhz that would represent a ~15% deviation in system clocks. 

Did you use a bootloader to upload the firmware?

It is feasible that IR remote control could work with a 15% inaccuracy, but from memory Serial can only tolerate up to ~+/-3% deviation (usually, depending on rate).

I guess if you recorded a signal with a 15% faster clock and resent it with the same 15% faster clock it would be similar to the way an accurate clock would work (for pulse timings but not carrier freq which is usually internal to the IR Reciver only.). However, serial BAUD rate would be a dfifferent matter. Similarly, sending or receiveng a signal that is 15% out in terms of timings and carrier frequency....could also work out at the cost of reduced performance & range. I can see how some protocols could work but some more challenging protocols woud not work.

**TIP:** In general, users should stick with standard configurations when using IRremote. (e.g. a standard 16MHz crystal or resonator costs <US$0.10)

**Comment by nedoskiv** [comment]
well I try it with 16MHz, works fine too
I do not send in my code, only receive. A little bit long, but here it is:

`// custom remote control by v_armenchev@yahoo.com

#define btn1 0xFFA25D
#define btn2 0xFF629D
#define btn3 0xFFE21D
#define btn4 0xFF22DD
#define btn5 0xFF02FD
#define rpt 0xFFFFFFFF

#define volup 0xFF18E7
#define volup1 0xFF5AA5
#define voldown 0xFF4AB5
#define voldown1 0xFF10EF
#define but0 0xFF9867

#define ON HIGH
#define OFF LOW

#define volumelenght 4
#define maxvolume 15
#define minvolume 0
int volume=9; // default volume
const byte  volumepattern[16][4] PROGMEM = {
 {ON,ON,ON,ON},
 {OFF,ON,ON,ON},
 {ON,OFF,ON,ON},
 {OFF,OFF,ON,ON},
 {ON,ON,OFF,ON},
 {OFF,ON,OFF,ON},
 {ON,OFF,OFF,ON},
 {OFF,OFF,OFF,ON},
 {ON,ON,ON,OFF},
 {OFF,ON,ON,OFF},
 {ON,OFF,ON,OFF},
 {OFF,OFF,ON,OFF},
 {ON,ON,OFF,OFF},
 {OFF,ON,OFF,OFF},
 {ON,OFF,OFF,OFF},
 {OFF,OFF,OFF,OFF}       
};
const byte  volumepins[4] PROGMEM = {19,18,17,16};

#define inputlenght 5
int input=0; // default volume
const byte  inputpattern[5][5] PROGMEM = {
 {ON,OFF,OFF,OFF,OFF},
 {OFF,ON,OFF,OFF,OFF},
 {OFF,OFF,ON,OFF,OFF},
 {OFF,OFF,OFF,ON,OFF},
 {OFF,OFF,OFF,OFF,ON}
};
const byte  inputpins[5] PROGMEM = {13,12,11,10,9};

const int powerpin=15;
int power=ON;

const int mutepin=14;
int mute;

unsigned long repeatmillis=0;
unsigned long repeatpreviousmillis=0;
unsigned int repeatrate=250;
unsigned long int remotecode;
unsigned long int lastremotecode=0;
#include <IRremote.h>

int RECV_PIN = 4;

IRrecv irrecv(RECV_PIN);
decode_results results;

void toggleinput(byte index, byte override)
{
 if ((override==1) || (index != input))
      {
        //Serial.print(F("Input changed to: "));
        //Serial.println(index);
        for (int i = 0; i <= inputlenght -1; i++)
            {
            digitalWrite(pgm_read_byte_near(&(inputpins[i])) , pgm_read_byte_near(&(inputpattern[index][i])));
            //Serial.print(F("PIN: "));
            //Serial.print(pgm_read_byte_near(&(inputpins[i])));
            //Serial.print(F(" state: "));
            //Serial.println(pgm_read_byte_near(&(inputpattern[index][i])));
            }
      input=index;
      }
 else
      {
       //Serial.println(F("Input state same, skip change!")); 
      }

}

void togglevolume(byte index, byte override)
{

 if ((override==1) || (index != volume))
      {
//        if (mute==OFF)
//            {
            //Serial.print(F("Vulume changed to: "));
            //Serial.println(index);
            for (int i = 0; i <= volumelenght -1; i++)
                {
                digitalWrite(pgm_read_byte_near(&(volumepins[i])) , pgm_read_byte_near(&(volumepattern[index][i])));
                //Serial.print(F("PIN: "));
                //Serial.print(pgm_read_byte_near(&(volumepins[i])));
                //Serial.print(F(" state: "));
                //Serial.println(pgm_read_byte_near(&(volumepattern[index][i])));
                }
//            volume=index;
//            }
//        else
//            {
//            //Serial.println(F("Volume muted, skip change!")); 
//            }
      }
 else
      {
//       //Serial.println(F("Volume state same, skip change!")); 
      }

}
void volumeup()
{

 mute=digitalRead(mutepin);
 if (mute==ON)
  {
  //Serial.println(F("[ VOLUMEUP ] Mute active!"));
  togglevolume(0,0);
  }
  else
   {
   int newvolume=volume+1;
   if (newvolume>maxvolume)
      {
      newvolume=maxvolume;
      }
   togglevolume(newvolume,0);
   volume=newvolume;
   }
}
void volumedown()
{

 mute=digitalRead(mutepin);
 if (mute==ON)
  {
  //Serial.println(F("[ VOLUMEDOWN ] Mute active!"));
  togglevolume(0,0);
  }
  else
   {
   int newvolume=volume-1;
   if (newvolume<minvolume)
      {
      newvolume=minvolume;
      }
   togglevolume(newvolume,0);
   volume=newvolume;

   }
}
void setup()
{
  
  //Serial.begin(9600);
  // In case the interrupt driver crashes on setup, give a clue
  // to the user what's going on.
  //Serial.println(F("Enabling IRin"));
  irrecv.enableIRIn(); // Start the receiver
  //Serial.println(F("Enabled IRin"));
  
        //Serial.println(F("Initializing input selector pins:"));
        for (int i = 0; i <= inputlenght -1; i++)
            {
            pinMode(pgm_read_byte_near(&(inputpins[i])) , OUTPUT);
            //Serial.print(F("Input: "));
            //Serial.print(i);
            //Serial.print(F(" on PIN: "));
            //Serial.println(pgm_read_byte_near(&(inputpins[i])));
            }
            
        //Serial.println("Initializing volume selector pins:");
        for (int i = 0; i <= volumelenght -1; i++)
            {
            pinMode(pgm_read_byte_near(&(volumepins[i])) , OUTPUT);
            //Serial.print(F("Selector: "));
            //Serial.print(i);
            //Serial.print(F(" on PIN: "));
            //Serial.println(pgm_read_byte_near(&(volumepins[i])));
            }
 toggleinput(input,1);

 pinMode(powerpin , OUTPUT);
 digitalWrite(powerpin,power);
 //Serial.print(F("Power pin: "));
 //Serial.print(powerpin);
 //Serial.print(F(" set to: "));
 //Serial.println(power);
 pinMode(mutepin, INPUT);
 mute=digitalRead(mutepin);
 //Serial.print(F("Mute toggle pin: "));
 //Serial.print(mutepin);
 //Serial.print(F(" read: "));
 //Serial.println(mute);
 if (mute==ON)
   {
//  //Serial.println(F("Mute active!"));
   togglevolume(0,1); //setup
   }
  else
   {
   togglevolume(volume,1); //setup
   }
 
}

void loop() {
  repeatmillis= millis();
  if (irrecv.decode(&results))
      {
        //Serial.println(results.value, HEX);
        irrecv.resume();
        remotecode=results.value;
        
        if (remotecode==rpt)
        {
        //   //Serial.println(F("RPT!"));
        // //Serial.println(repeatmillis);
        // //Serial.println(repeatpreviousmillis);
        // //Serial.println(repeatrate);
        if ((unsigned long)(repeatmillis - repeatpreviousmillis) >= repeatrate)
          {
            //Serial.println(F("REPEAT-----------------------!"));
           repeatpreviousmillis= millis();
           repeatmillis=repeatpreviousmillis;
           if ((lastremotecode==volup)||(lastremotecode==volup1)||(lastremotecode==voldown)||(lastremotecode==voldown1))    // change code only on volume button hold!
              {
              remotecode=lastremotecode;
              }
          }
        }
     if (remotecode !=rpt) 
         {
          lastremotecode=remotecode;
          repeatpreviousmillis= millis();
    repeatmillis=repeatpreviousmillis;    
         }
      else
        {
        }   
     switch(remotecode) {
       case btn1:
          input=0;
          toggleinput(input,1);
          break;
       case btn2:
          input=1;
          toggleinput(input,1);
          break;
       case btn3:
          input=2;
          toggleinput(input,1);
          break; 
       case btn4:
          input=3;
          toggleinput(input,1);
          break; 
       case btn5:
          input=4;
          toggleinput(input,1);
          break; 
       case volup:
          volumeup();
          break;
       case volup1:
          volumeup();
          break;
       case voldown:
          volumedown();
          break;
       case voldown1:
          volumedown();
          break;
       case but0:
          power=1-(1*power);
          digitalWrite(powerpin,power);
          //Serial.print(F("Power pin: "));
          //Serial.print(powerpin);
          //Serial.print(F(" set to: "));
          //Serial.println(power);
          break;          
    }
         
      }
  else
      {
      // repeatpreviousmillis= millis();
      // repeatmillis=repeatpreviousmillis;
      // lastremotecode=0;
      }
  
//return;
 mute=digitalRead(mutepin);
 if (mute==ON)
  {
//  //Serial.println(F("Mute active!"));
  togglevolume(0,0);
  }
  else
   {
   togglevolume(volume,0);
   }
//delay(1000);
}`

**Comment by AnalysIR** [comment]
OK  - thanks for that...

I note you have commented out all the Serial stuff.

As you are receiving only, the IR receiver takes care of the IR carrier - so crystal speed doesn't matter for this scenario. 

The signal's pulse timings will be ~15% off (shorter). However, Many IR protocol decoders will handle 15% innacuracies fine (introduced by the wrong crystal), but others will not.

(FYI: The IR receiver can distort pulse lenghts by up to +/-200uSecs in addition)

Nontheless, an interesting result and something to bear in mind for the future. 

However, IRremote users should stick with standard crystal/Arduino settings & configurations to avoid the 'potential' for obscure behaviour.

**Comment by nedoskiv** [comment]
it works fine on arduino board, when processor is alone there is no serial, so I comment it.
