### ISSUE TITLE
stm32 board

### ISSUE THREAD

**Issue by mal19992** [z3t0/Arduino-IRremote#679]
Can you add STM32 board to the library. Looking at https://github.com/KiLLAAA/Arduino-IRremote that is based on old version and works OK for my stm32, the difference between 2.3 and it is just 4 small patches:
<pre>
--- Arduino-IRremote-master-2.3/boarddefs.h     2018-03-13 00:17:02.000000000 +0300
+++ Arduino-IRremote-master-2.3-stm/boarddefs.h 2020-03-04 13:08:27.464783878 +0300
@@ -46,6 +46,13 @@
 #      define BLINKLED        255
 #      define BLINKLED_ON()   1
 #      define BLINKLED_OFF()  1
+
+//
+#elif defined (__STM32F1__)
+#  define BLINKLED        PC13
+# define BLINKLED_ON()   (digitalWrite(BLINKLED, HIGH))
+# define BLINKLED_OFF()  (digitalWrite(BLINKLED, LOW))
+
 #else
 #      define BLINKLED        13
 #      define BLINKLED_ON()  (PORTB |= B00100000)
@@ -146,6 +153,10 @@
 
 #elif defined(ESP32)
        #define IR_TIMER_USE_ESP32
+
+#elif defined(__STM32F1__)
+        #define IR_TIMER_USE_STM32F1XX
+
 #else
 // Arduino Duemilanove, Diecimila, LilyPad, Mini, Fio, Nano, etc
 // ATmega48, ATmega88, ATmega168, ATmega328
@@ -586,6 +597,16 @@
 #define TIMER_INTR_NAME      
 
 //---------------------------------------------------------
+// STM32F1XX
+#elif defined(IR_TIMER_USE_STM32F1XX)
+#define TIMER_RESET       
+#define TIMER_ENABLE_PWM     
+#define TIMER_DISABLE_PWM   Serial.println("IRsend not implemented for STM32F1XX yet");
+#define TIMER_ENABLE_INTR    
+#define TIMER_DISABLE_INTR   
+#define TIMER_INTR_NAME
+
+//---------------------------------------------------------
 // Unknown Timer
 //
 #else
--- Arduino-IRremote-master-2.3/IRremote.cpp    2018-03-13 00:17:02.000000000 +0300
+++ Arduino-IRremote-master-2.3-stm/IRremote.cpp        2020-03-04 13:16:05.918749687 +0300
@@ -123,7 +123,7 @@
 // As soon as first MARK arrives:
 //   Gap width is recorded; Ready is cleared; New logging starts
 //
-#ifdef IR_TIMER_USE_ESP32
+#if defined (IR_TIMER_USE_ESP32) || defined (IR_TIMER_USE_STM32F1XX)
 void IRTimer()
 #else
 ISR (TIMER_INTR_NAME)
--- Arduino-IRremote-master-2.3/irSend.cpp      2018-03-13 00:17:02.000000000 +0300
+++ Arduino-IRremote-master-2.3-stm/irSend.cpp  2020-03-04 13:13:39.626440935 +0300
@@ -55,7 +55,7 @@
 void  IRsend::enableIROut (int khz)
 {
 // FIXME: implement ESP32 support, see IR_TIMER_USE_ESP32 in boarddefs.h
-#ifndef ESP32
+#if !defined (ESP32) && !defined (__STM32F1__)
        // Disable the Timer2 Interrupt (which is used for receiving IR)
        TIMER_DISABLE_INTR; //Timer2 Overflow Interrupt
 
--- ../aae/Arduino-IRremote-master/irRecv.cpp   2018-03-13 00:17:02.000000000 +0300
+++ Arduino-IRremote-master-2.3-stm/irRecv.cpp  2020-03-04 13:12:17.015266590 +0300
@@ -6,6 +6,11 @@
 void IRTimer(); // defined in IRremote.cpp
 #endif
 
+#ifdef IR_TIMER_USE_STM32F1XX
+HardwareTimer timer(2);
+void IRTimer(); // defined in IRremote.cpp
+#endif
+
 //+=============================================================================
 // Decodes the received IR message
 // Returns 0 if no data ready, 1 if data ready.
@@ -123,7 +128,7 @@
 void  IRrecv::enableIRIn ( )
 {
 // Interrupt Service Routine - Fires every 50uS
-#ifdef ESP32
+#if defined (ESP32)
        // ESP32 has a proper API to setup timers, no weird chip macros needed
        // simply call the readable API versions :)
        // 3 timers, choose #1, 80 divider nanosecond precision, 1 to count up
@@ -132,6 +137,24 @@
        // every 50ns, autoreload = true
        timerAlarmWrite(timer, 50, true);
        timerAlarmEnable(timer);
+#elif defined (__STM32F1__)
+
+#ifndef F_INTERRUPTS                                    // TODO: move to proper place or replace the variable
+#  define F_INTERRUPTS                          20000   // interrupts per second, min: 10000, max: 20000, typ: 15000
+#endif
+
+  timer.pause();
+  timer.setPrescaleFactor( ((SYSCLOCK / F_INTERRUPTS) / 8) - 1);
+  timer.setOverflow(7);
+  timer.setChannel1Mode(TIMER_OUTPUT_COMPARE);
+  timer.setCompare(TIMER_CH1, 1);  // Interrupt 1 count after each update
+  timer.attachCompare1Interrupt(IRTimer);
+  // Refresh the timer's count, prescale, and overflow
+  timer.refresh();
+
+  // Start the timer counting
+  timer.resume();
+  
 #else
        cli();
        // Setup pulse clock timer interrupt
</pre>

It is very minor, localized and worth including

**Comment by ArminJo** [comment]
STM32 is supported by the [IRMP](https://github.com/ukw100/IRMP#version-121) Arduino Library.
Instruction for esy porting you can find [here](https://github.com/ukw100/IRMP#easy-migrating-your-code-from-irremote-to-irmp).
