### ISSUE TITLE
IRremote on Webserver

### ISSUE THREAD

**Issue by cylon147** [z3t0/Arduino-IRremote#684]
I am trying to find an online web server that provides all the AC codes to use with a Home Automation system, I have searched everywhere but didn't come across anything related to this.

Basically I am looking for a Webserver with API to which I can Pass Brand and Remote model number to get All the IR codes in JSON formate.

Please help me out with this.

**Comment by AnalysIR** [comment]
AFAIK....not available anywhere.
We have a lot of commercial users worldwide who use our AnalysIR application & IR modules to build their own database of signals for use in their commercial products.

**Comment by cylon147** [comment]
Great. Can you please provide more information on Commercial Product and guide me how to build our own database.

**Comment by AnalysIR** [comment]
[Contact via](https://www.analysir.com/blog/contact/)

...as it would be off-topic here

**Comment by cylon147** [comment]
Request sent...
