### ISSUE TITLE
All IR decoding is broken in the master branch 

### ISSUE THREAD

**Issue by pvdbrand** [z3t0/Arduino-IRremote#700]
The commit 76f233faddfbaba9bf27d318bc22a0d7fb71e772 (13 days ago) seems to have completely broken all IR decoding, on all boards and for all protocols.

Old code in MATCH_MARK() in IRremote.cpp:
```
bool passed = ((measured_ticks >= TICKS_LOW (desired_us + MARK_EXCESS))
                && (measured_ticks <= TICKS_HIGH(desired_us + MARK_EXCESS)));
```
New code since that commit:
```
    int compensated_ticks = measured_ticks - MARK_EXCESS; // compensate for marks exceeded by demodulator hardware
    bool passed = ((compensated_ticks >= TICKS_LOW(desired_us)) && (compensated_ticks <= TICKS_HIGH(desired_us)));
```

This code is not equivalent and it will make all matches fail. There are several more changes in that commit that I have not checked. They may be wrong too.

**Comment by ArminJo** [comment]
Why is it not equivalent? Please prove.

**Comment by AnalysIR** [comment]
Is **MARK_EXCESS** defined as  uSecs?
Is compensated_ticks  defined as ticks?

**Comment by ArminJo** [comment]
Thanks, thats the fault!

**Comment by ArminJo** [comment]
@pvdbrand 🥇  
Thank you very much for reporting this bug!!!
