### ISSUE TITLE
ATmega328PB support

### ISSUE THREAD

**Issue by AnalysIR** [z3t0/Arduino-IRremote#707]
@ArminJo 

There is currently no declaration for ATmega328PB in IRremoteBoardDefs.h

For IRremote it is essentially identical to ATmega328P (with a few more GPIO pins & peripherals & is lower in price)

It would be useful if you could add the following to line number 179 in IRremoteBoardDefs.h...next time you are making an update.

`#elif defined(__AVR_ATmega328P__) || defined(__AVR_ATmega328PB__) || defined(__AVR_ATmega168__) // old default clause`

In a similar way.....would it be better to replace the #error msg with a #warning msg & leave the #define for Timer1 in place....around line number 179 in IRremoteBoardDefs.h as follows

```
#else
// Arduino Duemilanove, Diecimila, LilyPad, Mini, Fio, Nano, etc
// ATmega48, ATmega88, ATmega168, ATmega328
#define IR_USE_TIMER1   // tx = pin 9
//#define IR_USE_TIMER2   // tx = pin 3
#warning Board could not be identified from pre-processor symbols. By Default, TIMER1 has been selected for use with IRremote.
#endif
```
FYI: I have used the ATmega328PB sucessfully with IRremote.... a lot & it works fine by just defining TIMER1 (or Timer2) as above.

**Comment by ArminJo** [comment]
Hi, thanks for the suggestions.
