### ISSUE TITLE
How to change timer used in IRremote.h library for ESP32

### ISSUE THREAD

**Issue by johnathanmika** [z3t0/Arduino-IRremote#712]
### Board
* [ ] Arduino ATmega328* board (UNO, Nano)
* [ ] Arduino ATmega2560 board (Mega)
* [ ] Arduino ATmega32U4 board (Leonardo)
* [ ] Arduino SAM board (Due)
* [ ] Arduino SAMD board (Zero, MKR*)
* [X] ESP32 board
* [ ] Teensy board
* [ ] Other - please specify

### Protocol
* [x] Unknown
* [ ] Aiwa
* [ ] BoseWave
* [ ] Denon
* [ ] Dish
* [ ] JVC
* [ ] Lego
* [ ] LG
* [ ] Mitsubishi
* [ ] Panasonic
* [ ] RC5, RC6
* [ ] Samsung
* [ ] Sanyo
* [ ] Sharp
* [ ] Sony
* [ ] Whynter
* [ ] Other - please specify

**Code Block:**

#include <IRremote.h> 
#include <PxMatrix.h>
//These two libraries are incompatible due to timers
//I would like to change the timer
//I searched the IRremoteBoardDefs.h file
//How do I change IR_USE_TIMER_ESP32 to another timer on the ESP32?
//Link to IRremoteBoardDefs.h file https://github.com/z3t0/Arduino-IRremote/blob/master/src/private/IRremoteBoardDefs.h

**checklist:**
- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] The latest [release](https://github.com/z3t0/Arduino-IRremote/releases/latest) is used
- [X] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here
- [X] The title of the issue is helpful and relevant

**Comment by ArminJo** [comment]
Please look at https://github.com/crankyoldgit/IRremoteESP8266 or in the esp32.cpp file.
