### ISSUE TITLE
Dynamically changing TX PIN

### ISSUE THREAD

**Issue by mrscarvalho** [z3t0/Arduino-IRremote#714]
Board: Pro Micro (Atmega32u4)
Protocol: NEC*
IRremote Version 2.0.1

I could change the boarddefs.h to change the default pin for Atmega32u4 from 13 to 9, since this board has not pin 13. (I know newer versions of the library already support this board now - I'll try them soon)

But I'd like to be able to change the transmission PIN dynamically, to be able to control (independently, not colectivelly) several devices with a single board, choosing what device to control, being able at least to use all the 5 PWM outputs of this board.

Is there some way to send the PIN number as a parameter instead defining it using #DEFINE static directives?

Thanks!

_*The one that worked, as I could not find the actual manufacturer of some devices used by Cable TV operators or DTV STBs. Probably my changes did the library not work with any other board, as I was just trying and testing, not really aware of what I was doing..._

**Comment by ArminJo** [comment]
Try [IRMP](https://github.com/ukw100/IRMP), it can change pins dynamically.
