### ISSUE TITLE
How to swich between protocols in Arduino-IRremote library ?

### ISSUE THREAD

**Issue by maciokeks** [z3t0/Arduino-IRremote#718]
### Board
* [ ] Arduino ATmega328* board (UNO, Nano)
* [ ] Arduino ATmega2560 board (Mega)
* [ ] Arduino ATmega32U4 board (Leonardo)
* [ ] Arduino SAM board (Due)
* [ ] Arduino SAMD board (Zero, MKR*)
* [ ] ESP32 board - first check https://github.com/crankyoldgit/IRremoteESP8266
* [ ] Teensy board
* [x] Other - please specify - esp8266  

### Protocol
* [ ] Unknown
* [ ] Aiwa
* [ ] BoseWave
* [ ] Denon
* [ ] Dish
* [ ] JVC
* [ ] Lego
* [ ] LG
* [ ] Mitsubishi
* [ ] Panasonic
* [ ] RC5, RC6
* [ ] Samsung
* [ ] Sanyo
* [ ] Sharp
* [ ] Sony
* [ ] Whynter
* [x] Other - please specify - all protocols

**Code Block:**
```c

#include <IRremote.h> 
irsend.send(protocol , code , lenght);

```

Use [a gist](gist.github.com) if the code exceeds 30 lines

**checklist:**
- [x] I have **read** the README.md file thoroughly
- [x] I have searched existing issues to see if there is anything I have missed.
- [x] The latest [release](https://github.com/z3t0/Arduino-IRremote/releases/latest) is used
- [x] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here
- [x] The title of the issue is helpful and relevant 

The above is a short template allowing you to make detailed issues!
How I can switch the protocols using variable on ```irsend.send(protocols, codeforsend ,lenght);``` without any debugger errors? How I can declare to make it work?

**Comment by AnalysIR** [comment]
the syntax is generally irsend**XXX**(...)
where **XXX** is the protocol name.

you need to ensure the individual protocols are enabled/disabled in IRremote.h as required.

The method you outined aboed is not supported, to ensure the sketch compiles to the smallest size on common MCUs

Also check out the examples provided.
