### ISSUE TITLE
Receiver examples stopped working in Teensy 3.2

### ISSUE THREAD

**Issue by morusa** [z3t0/Arduino-IRremote#719]
Hi,

the teensy (3.2) board gets stuck when trying to run:

IrReceiver.enableIRIn();

regards

**Comment by ArminJo** [comment]
Use [IRMP](https://github.com/ukw100/IRMP), Teensy 3.2 is not supported by IRremote.

**Comment by bengtmartensson** [comment]
Teensy 3.2 is almost identical to 3.1, which is supported according to the README. @PaulStoffregen, are you there?

Teensy 3.1-2 is also supported by [Infrared4Arduino](https://github.com/bengtmartensson/Infrared4Arduino).
