### ISSUE TITLE
May be a bug

### ISSUE THREAD

**Issue by jhao-x** [z3t0/Arduino-IRremote#723]
file:
    IRremote.c
funciton:
    ISR
problem:
irparams.timer++ have no limit, when timer counter overflow
meet the ir mark receiving will miss the this ir signal

**Comment by ArminJo** [comment]
And you encountered this bug?
Which protocol?

**Comment by jhao-x** [comment]
> And you encountered this bug?
> Which protocol?
This is the public receiving part, not a certain protocol.
If this is not a bug, how to solve the overflow problem?

**Comment by ArminJo** [comment]
What problem?
