### ISSUE TITLE
printIRResultRawFormatted printIRResultAsCArray output

### ISSUE THREAD

**Issue by MrYellowSock** [z3t0/Arduino-IRremote#729]
```
aSerial->print(results.rawlen - 1, DEC);    // array size
    aSerial->print("] = {");                    // Start declaration

// Dump data
    for (unsigned int i = 1; i < results.rawlen; i++) 
```
why first index is removed? when i use result from **printIRResultAsCArray** or **printIRResultRawFormatted** on sendRaw my device will not work. But if i use result from **printIRResultRaw** everything works fine.

**Comment by ArminJo** [comment]
Thank you very much to point out this inconsistency 🥇
