### ISSUE TITLE
Swapped cases / #ifs

### ISSUE THREAD

**Issue by Jim-2249** [z3t0/Arduino-IRremote#731]
Line 406 of irReceive.cpp LEGO_PF & LG appear to have swapped **case LG:** and **case LEGO_PF:** lines

```
#if DECODE_LEGO_PF
    case LG:
        return ("LEGO");
        break;
#endif
#if DECODE_LG
    case LEGO_PF:
        return ("LEGO_PF");
        break;
#endif
```

**Comment by maa1370** [comment]
and LG case should return "LG", not "LEGO"

#if DECODE_LG
    case LG:
        return("LG");
        break;
#endif
#if DECODE_LEGO_PF
    case LEGO_PF:
        return ("LEGO_PF");
        break;
#endif

**Comment by ArminJo** [comment]
Thanks! 🥇
