### ISSUE TITLE
'TKD2' was not declared in this scope

### ISSUE THREAD

**Issue by farzher** [z3t0/Arduino-IRremote#98]
![arduinounoerror](https://cloud.githubusercontent.com/assets/1005136/5059405/ef50c150-6ce7-11e4-903e-ad6eaf1a24d8.PNG)

**Comment by sandhysanjaya** [comment]
Hai, Just rename your Folder library... Like this From "IR" to "IRremote"
thats default i think

**Comment by joshuajnoble** [comment]
Yes, it's out of our hands unless we rename the whole library, which I'd prefer not to do.

**Comment by Bharadwaj1** [comment]
hi, I've problem with my arduino software regarding TKD2 error . as lichtteil said that I've removed my RobotIRremote out of the Arduino-libraries folder but its not working and still displays an error. I request anyone, please resolve my problem.
![issue](https://cloud.githubusercontent.com/assets/25689138/22830394/638103c8-efcc-11e6-9ce4-113b261dc3dc.PNG)

**Comment by Bharadwaj1** [comment]
![issue2](https://cloud.githubusercontent.com/assets/25689138/22830523/d7866e70-efcc-11e6-9d95-c002ccfd78ab.PNG)

**Comment by AnalysIR** [comment]
@Bharadwaj1 

did you try restarting the IDE?

**Comment by Bharadwaj1** [comment]
Yes I've did it sir

**Comment by Bharadwaj1** [comment]
I've downloaded the arduino IR remote master from  this website..but my error when RobotIRremote out of the Arduino-libraries folder it shows the error.

C:\Program Files\Arduino\examples\Arduino-IRremote-master\examples\IRrecvDemo\IRrecvDemo.ino:9:22: fatal error: IRremote.h: No such file or directory

**Comment by z3t0** [comment]
Please copy it to arduino/libraries not examples in your documents directory

**Comment by ramnath555** [comment]
A simple solution... open IRremoteTools.cpp which is in "C:\Program Files\Arduino\libraries\RobotIRremote\src"  and replace TKD2 with any number. I put 1. now try arduino .. it works great!!!!

**Comment by z3t0** [comment]
@ramnath555 A better solution is to remove RobotIRremote altogether

**Comment by ramnath555** [comment]
Removing "RobotIRremote" will give  "'IRremote.h' not found" - :) .   It you use older IRLib.h then most of the remotes will give 0 value for all keys

**Comment by z3t0** [comment]
You should not be using robotics irremote along with this library. They conflict

**Comment by marcmerlin** [comment]
@z3t0 :  So, I've read the multiple issues on this over the last 2 years.
It's easy enough for everyone to delete arduino-xxx/libraries/RobotIRremote/ every time they install or upgrade the arduino IDE, but really this is not a fix.
When I give my code around, everyone is going to hit this problem.
I realize it's not your fault but it seems that in the last 2 years, the arduino folks have not fixed anything to make your library work out of the box again.
Now the part I don't even understand is that in one of my programs, it does
 Used: /var/local/arduino-1.8.2/libraries/RobotIRremote
 Not used: /home/merlin/Arduino/libraries/Arduino-IRremote
and in the other one, it goes the other way around (randomly?) and works.

Of course, there seems to be no way to force the IDE to use my local libraries over its own, and it still ignores include "foo." vs include <foo.h> it seems when it could have used it as a hint/workaround.

So, is there really no long term fix to this? Everyone must delete libraries/RobotIRremote forever on every copy of the arduino IDE they ever install?
If so, would it be easier to have the library just rename its IRremote.h to RealIRremote.h or somesuch to work around the issue?

**Comment by z3t0** [comment]
@marcmerlin You have made a really good point that honestly I have never considered! I very rarely update Arduino and I don't even recall if I needed to delete RobotIRremote the last time. But considering what you have said I will certainly find a way to fix this. If I recall, the issue was that RobotIRremote was initially a fork of this library (or something like that) and so there are symbols that are duplicates in both instances. I will go ahead and prioritize this as a new issue

**Comment by dmccreary** [comment]
It took me about an hour, but I finally figured out a solution.  On the Mac I used the Terminal application and did a "cd /Applications/Arduino.app" followed by an "open .".  That opened up the Finder inside the Arduino application.  I then navigated to the contents/Java/libraries and removed the RobotIRRemote folder.  I then went to main Arduino/Sketch/Include Library.../Manage Libraries and did a search for the IRRemote library.  After I imported that the libraries complied without any problem!

I did try several other suggestions mentioned above.  However, each of them failed.

For other instructions we will include this fix in the CoderDojo robot book.

**Comment by khaldon** [comment]
I have the same problem and until now I can't solve it my project is stopped because the IR

**Comment by AnalysIR** [comment]
1. It seems this issue was closed & you should open a new one & refer back to this one
2. If you have the same problem the solution is likely above.
3. If not, a search is bound to show a solution for this problem
4. More importantly, you have not provided any meaningful explanation of your problem (_or what steps you have taken to try to resolve your problem_), to allow other to assist.

**Comment by HaGaDIY** [comment]
I have encountered the same problem. corrected and successful
Step 1: Download and install. Sketch ---> Include Library ---> Add Library https://github.com/shirriff/Arduino-IRremote/
Step 2: Remove the RobotIRremote library in the Arduino.
Step 3: Compile and succeed

**Comment by tytower** [comment]
Seems to be fixed in the latest IDE
